#ifndef _ALARMDISPOSEPAGE_H_
#define _ALARMDISPOSEPAGE_H_

#include "ui.h"

#define IDC_STATIC_ALARMDISPOSE_RECORDCHN		IDD_DIALOG_ALARMDISPOSE+1

#define IDC_STATIC_ALARMDISPOSE_RECORDCHN1		IDD_DIALOG_ALARMDISPOSE+2
#define IDC_STATIC_ALARMDISPOSE_RECORDCHN2		IDD_DIALOG_ALARMDISPOSE+3
#define IDC_STATIC_ALARMDISPOSE_RECORDCHN3		IDD_DIALOG_ALARMDISPOSE+4
#define IDC_STATIC_ALARMDISPOSE_RECORDCHN4		IDD_DIALOG_ALARMDISPOSE+5

#define IDC_CHECK_ALARMDISPOSE_RECORDCHN1		IDD_DIALOG_ALARMDISPOSE+6
#define IDC_CHECK_ALARMDISPOSE_RECORDCHN2		IDD_DIALOG_ALARMDISPOSE+7
#define IDC_CHECK_ALARMDISPOSE_RECORDCHN3		IDD_DIALOG_ALARMDISPOSE+8
#define IDC_CHECK_ALARMDISPOSE_RECORDCHN4		IDD_DIALOG_ALARMDISPOSE+9

#define IDC_STATIC_ALARMDISPOSE_SOUNDALARM		IDD_DIALOG_ALARMDISPOSE+10
#define IDC_STATIC_ALARMDISPOSE_CENTER			IDD_DIALOG_ALARMDISPOSE+11
#define IDC_STATIC_ALARMDISPOSE_OUT				IDD_DIALOG_ALARMDISPOSE+12

#define IDC_STATIC_ALARMDISPOSE_OUT1			IDD_DIALOG_ALARMDISPOSE+13
#define IDC_STATIC_ALARMDISPOSE_OUT2			IDD_DIALOG_ALARMDISPOSE+14
#define IDC_STATIC_ALARMDISPOSE_OUT3			IDD_DIALOG_ALARMDISPOSE+15
#define IDC_STATIC_ALARMDISPOSE_OUT4			IDD_DIALOG_ALARMDISPOSE+16

#define IDC_CHECK_ALARMDISPOSE_SOUNDALARM		IDD_DIALOG_ALARMDISPOSE+17
#define IDC_CHECK_ALARMDISPOSE_CENTER			IDD_DIALOG_ALARMDISPOSE+18
#define IDC_CHECK_ALARMDISPOSE_OUT				IDD_DIALOG_ALARMDISPOSE+19

#define IDC_CHECK_ALARMDISPOSE_OUT1				IDD_DIALOG_ALARMDISPOSE+20
#define IDC_CHECK_ALARMDISPOSE_OUT2				IDD_DIALOG_ALARMDISPOSE+21
#define IDC_CHECK_ALARMDISPOSE_OUT3				IDD_DIALOG_ALARMDISPOSE+22
#define IDC_CHECK_ALARMDISPOSE_OUT4				IDD_DIALOG_ALARMDISPOSE+23

#define IDC_BUTTON_ALARMDISPOSE_OK				IDD_DIALOG_ALARMDISPOSE+24
#define IDC_BUTTON_ALARMDISPOSE_CANCEL			IDD_DIALOG_ALARMDISPOSE+25

BOOL CreateAlarmdisposePage();
BOOL ShowAlarmdisposePage();

u8 GetAlarmInputDisposeID();
void SetAlarmInputDisposeID(u8 id);

#endif
