#ifndef _ALARMTIMEPAGE_H_
#define _ALARMTIMEPAGE_H_

#include "ui.h"

#define IDC_STATIC_ALARMTIME_DATE					IDD_DIALOG_ALARMTIME+1
#define IDC_COMBO_ALARMTIME_DATE					IDD_DIALOG_ALARMTIME+2

#define IDC_STATIC_ALARMTIME_TIMESECTION1			IDD_DIALOG_ALARMTIME+3
#define IDC_EDIT_ALARMTIME_STARTTIME1				IDD_DIALOG_ALARMTIME+4
#define IDC_EDIT_ALARMTIME_ENDTIME1					IDD_DIALOG_ALARMTIME+5

#define IDC_STATIC_ALARMTIME_TIMESECTION2			IDD_DIALOG_ALARMTIME+6
#define IDC_EDIT_ALARMTIME_STARTTIME2				IDD_DIALOG_ALARMTIME+7
#define IDC_EDIT_ALARMTIME_ENDTIME2					IDD_DIALOG_ALARMTIME+8

#define IDC_STATIC_ALARMTIME_TIMESECTION3			IDD_DIALOG_ALARMTIME+9
#define IDC_EDIT_ALARMTIME_STARTTIME3				IDD_DIALOG_ALARMTIME+10
#define IDC_EDIT_ALARMTIME_ENDTIME3					IDD_DIALOG_ALARMTIME+11

#define IDC_STATIC_ALARMTIME_TIMESECTION4			IDD_DIALOG_ALARMTIME+12
#define IDC_EDIT_ALARMTIME_STARTTIME4				IDD_DIALOG_ALARMTIME+13
#define IDC_EDIT_ALARMTIME_ENDTIME4					IDD_DIALOG_ALARMTIME+14

#define IDC_STATIC_ALARMTIME_COPY					IDD_DIALOG_ALARMTIME+15
#define IDC_COMBO_ALARMTIME_COPY					IDD_DIALOG_ALARMTIME+16
#define IDC_BUTTON_ALARMTIME_COPY					IDD_DIALOG_ALARMTIME+17
#define IDC_BUTTON_ALARMTIME_OK						IDD_DIALOG_ALARMTIME+18
#define IDC_BUTTON_ALARMTIME_CANCEL					IDD_DIALOG_ALARMTIME+19
#define IDC_CHECK_ALARMTIM_WHOLEDAY					IDD_DIALOG_ALARMTIME+20
#define IDC_COMBO_ALARMTIME_TIMETYPE				IDD_DIALOG_ALARMTIME+21
#define IDC_CHECK_ALARMTIME_TIMESECTION1            IDD_DIALOG_ALARMTIME+22
#define IDC_DATETIME_ALARMTIME_STARTTIME1           IDD_DIALOG_ALARMTIME+23
#define IDC_DATETIME_ALARMTIME_ENDTIME1             IDD_DIALOG_ALARMTIME+24
#define IDC_CHECK_ALARMTIME_TIMESECTION2            IDD_DIALOG_ALARMTIME+25
#define IDC_DATETIME_ALARMTIME_STARTTIME2           IDD_DIALOG_ALARMTIME+26
#define IDC_DATETIME_ALARMTIME_ENDTIME2             IDD_DIALOG_ALARMTIME+27
#define IDC_CHECK_ALARMTIME_TIMESECTION3            IDD_DIALOG_ALARMTIME+28
#define IDC_DATETIME_ALARMTIME_STARTTIME3           IDD_DIALOG_ALARMTIME+29
#define IDC_DATETIME_ALARMTIME_ENDTIME3             IDD_DIALOG_ALARMTIME+30
#define IDC_CHECK_ALARMTIME_TIMESECTION4            IDD_DIALOG_ALARMTIME+31
#define IDC_DATETIME_ALARMTIME_STARTTIME4           IDD_DIALOG_ALARMTIME+32
#define IDC_DATETIME_ALARMTIME_ENDTIME4             IDD_DIALOG_ALARMTIME+33
#define IDC_CHECK_ALARMTIME_COPY0                   IDD_DIALOG_ALARMTIME+34
#define IDC_CHECK_ALARMTIME_COPY1                   IDD_DIALOG_ALARMTIME+35
#define IDC_CHECK_ALARMTIME_COPY2                   IDD_DIALOG_ALARMTIME+36
#define IDC_CHECK_ALARMTIME_COPY3                   IDD_DIALOG_ALARMTIME+37
#define IDC_CHECK_ALARMTIME_COPY4                   IDD_DIALOG_ALARMTIME+38
#define IDC_CHECK_ALARMTIME_COPY5                   IDD_DIALOG_ALARMTIME+39
#define IDC_CHECK_ALARMTIME_COPY6                   IDD_DIALOG_ALARMTIME+40
#define IDC_CHECK_ALARMTIME_COPYOTHER               IDD_DIALOG_ALARMTIME+41
#define IDC_INPUTBOX_ALARMTIME_DENO               IDD_DIALOG_ALARMTIME+42


BOOL CreateAlarmtimePage();
BOOL ShowAlarmtimePage();

void GetAlarmTimeFlagAndID(u8 *pflag,u8 *pid);
void SetAlarmTimeFlagAndID(u8 flag,u8 id);

#endif
