#ifndef _ALARMPAGE_H_
#define _ALARMPAGE_H_

#include "ui.h"
#include "ctrlprotocol.h"

#define IDC_PROGRESS_ALARM_COMPART			IDD_DIALOG_ALARMIN+1

#define IDC_STATIC_ALARM_INPUTPIN				IDD_DIALOG_ALARMIN+2
#define IDC_STATIC_ALARM_ALARMTYPE			IDD_DIALOG_ALARMIN+3
#define IDC_STATIC_ALARM_DISPOSE				IDD_DIALOG_ALARMIN+4

#define IDC_COMBO_ALARM_INPUTPIN				IDD_DIALOG_ALARMIN+5
#define IDC_COMBO_ALARM_ALARMTYPE			IDD_DIALOG_ALARMIN+6
#define IDC_COMBO_ALARM_DISPOSE				IDD_DIALOG_ALARMIN+7

#define IDC_BUTTON_ALARM_SETTIME				IDD_DIALOG_ALARMIN+8
#define IDC_BUTTON_ALARM_MANAGE				IDD_DIALOG_ALARMIN+9
#define IDC_BUTTON_ALARM_PTZ					IDD_DIALOG_ALARMIN+10

#define IDC_STATIC_ALARM_COPY					IDD_DIALOG_ALARMIN+11
#define IDC_COMBO_ALARM_COPY					IDD_DIALOG_ALARMIN+12
#define IDC_BUTTON_ALARM_COPY					IDD_DIALOG_ALARMIN+13


#define IDC_BUTTON_ALARMIN_OK					IDD_DIALOG_ALARMIN+14
#define IDC_BUTTON_ALARMIN_CANCEL			IDD_DIALOG_ALARMIN+15

#define IDC_STATIC_ALARM_EMAIL				IDD_DIALOG_ALARMIN+16
#define IDC_CHECKBOX_ALARM_EMAIL				IDD_DIALOG_ALARMIN+17
#define IDC_STATIC_ALARM_ALARMBUZZER				IDD_DIALOG_ALARMIN+18
#define IDC_CHECKBOX_ALARMBUZZER				IDD_DIALOG_ALARMIN+19
#define IDC_STATIC_ALARM_REC				IDD_DIALOG_ALARMIN+20
#define IDC_CHECK_REC_CH1				IDD_DIALOG_ALARMIN+21
#define IDC_CHECK_REC_CH2				IDD_DIALOG_ALARMIN+22
#define IDC_CHECK_REC_CH3				IDD_DIALOG_ALARMIN+23
#define IDC_CHECK_REC_CH4				IDD_DIALOG_ALARMIN+24
#define IDC_CHECK_REC_CH5				IDD_DIALOG_ALARMIN+25
#define IDC_CHECK_REC_CH6				IDD_DIALOG_ALARMIN+26
#define IDC_CHECK_REC_CH7				IDD_DIALOG_ALARMIN+27
#define IDC_CHECK_REC_CH8				IDD_DIALOG_ALARMIN+28
#define IDC_CHECK_REC_CH9				IDD_DIALOG_ALARMIN+29
#define IDC_CHECK_REC_CH10			IDD_DIALOG_ALARMIN+30
#define IDC_CHECK_REC_CH11			IDD_DIALOG_ALARMIN+31
#define IDC_CHECK_REC_CH12			IDD_DIALOG_ALARMIN+32
#define IDC_CHECK_REC_CH13			IDD_DIALOG_ALARMIN+33
#define IDC_CHECK_REC_CH14			IDD_DIALOG_ALARMIN+34
#define IDC_CHECK_REC_CH15			IDD_DIALOG_ALARMIN+35
#define IDC_CHECK_REC_CH16			IDD_DIALOG_ALARMIN+36




#define IDC_STATIC_ALARMOUT_CH			IDD_DIALOG_ALARMIN+37
#define IDC_CHECK_ALARMOUT_CH1			IDD_DIALOG_ALARMIN+38
#define IDC_CHECK_ALARMOUT_CH2			IDD_DIALOG_ALARMIN+39
#define IDC_CHECK_ALARMOUT_CH3			IDD_DIALOG_ALARMIN+40
#define IDC_CHECK_ALARMOUT_CH4			IDD_DIALOG_ALARMIN+41
#define IDC_CHECK_ALARMOUT_CH5			IDD_DIALOG_ALARMIN+42
#define IDC_CHECK_ALARMOUT_CH6			IDD_DIALOG_ALARMIN+43
#define IDC_CHECK_ALARMOUT_CH7			IDD_DIALOG_ALARMIN+44
#define IDC_CHECK_ALARMOUT_CH8			IDD_DIALOG_ALARMIN+45
#define IDC_CHECK_ALARMOUT_CH9			IDD_DIALOG_ALARMIN+46
#define IDC_CHECK_ALARMOUT_CH10			IDD_DIALOG_ALARMIN+47
#define IDC_CHECK_ALARMOUT_CH11			IDD_DIALOG_ALARMIN+48
#define IDC_CHECK_ALARMOUT_CH12			IDD_DIALOG_ALARMIN+49
#define IDC_CHECK_ALARMOUT_CH13			IDD_DIALOG_ALARMIN+50
#define IDC_CHECK_ALARMOUT_CH14			IDD_DIALOG_ALARMIN+51
#define IDC_CHECK_ALARMOUT_CH15			IDD_DIALOG_ALARMIN+52
#define IDC_CHECK_ALARMOUT_CH16			IDD_DIALOG_ALARMIN+53
#define IDC_STATIC_ALARMIN_DELAY			IDD_DIALOG_ALARMIN+54
//#define IDC_BUTTON_ALARM_MAIL_SET		IDD_DIALOG_ALARMIN+55 //zlb20090915
#define IDC_COMBO_ALARMIN_DELAY			IDC_COMBO_ALARM_OUTPUTDELAY

#define IDC_STATIC_ALARM_PTZ				IDD_DIALOG_ALARMIN+56

#ifdef FTP_PIC
#define IDC_STATIC_ALARM_FTP				IDD_DIALOG_ALARMIN+59
#define IDC_CHECKBOX_ALARM_FTP				IDD_DIALOG_ALARMIN+60
#endif

#define IDD_DIALOG_ALARMIN_SETMAIL	IDD_DIALOG_ALARMIN+80
#define IDC_STATIC_ALARMIN_MAILADDR	IDD_DIALOG_ALARMIN_SETMAIL+1
#define IDC_EDIT_ALARMIN_MAILADDR		IDD_DIALOG_ALARMIN_SETMAIL+2
#define IDC_BUTTON_ALARMIN_MAIL_OK	IDD_DIALOG_ALARMIN_SETMAIL+3

#define IDC_STATIC_ALARMIN_ENABLE		IDD_DIALOG_ALARMIN_SETMAIL+4
#define IDC_COMBO_ALARMIN_ENABLE		IDD_DIALOG_ALARMIN_SETMAIL+5


 

#define IDC_STATIC_ALARM_OUTPUTPIN			IDD_DIALOG_ALARMOUT+1
#define IDC_STATIC_ALARM_OUTPUTTYPE			IDD_DIALOG_ALARMOUT+2
#define IDC_STATIC_ALARM_OUTPUTTIME			IDD_DIALOG_ALARMOUT+3
#define IDC_STATIC_ALARM_OUTPUTDELAY			IDD_DIALOG_ALARMOUT+4

#define IDC_COMBO_ALARM_OUTPUTPIN			IDD_DIALOG_ALARMOUT+4
#define IDC_COMBO_ALARM_OUTPUTTYPE			IDD_DIALOG_ALARMOUT+5
#define IDC_BUTTON_ALARM_OUTPUTTIME			IDD_DIALOG_ALARMOUT+6
#define IDC_COMBO_ALARM_OUTPUTDELAY			IDD_DIALOG_ALARMOUT+7

#define IDC_STATIC_ALARM_OUTPUTCOPY			IDD_DIALOG_ALARMOUT+8
#define IDC_COMBO_ALARM_OUTPUTCOPY			IDD_DIALOG_ALARMOUT+9
#define IDC_BUTTON_ALARM_OUTPUTCOPY			IDD_DIALOG_ALARMOUT+10

#define IDC_BUTTON_ALARMOUT_OK				IDD_DIALOG_ALARMOUT+11
#define IDC_BUTTON_ALARMOUT_CANCEL			IDD_DIALOG_ALARMOUT+12
//zlb20090915 begin
// #define IDC_STATIC_ALARMOUT_TIME1				IDD_DIALOG_ALARMOUT+13
// #define IDC_STATIC_ALARMOUT_TIME2				IDD_DIALOG_ALARMOUT+14
// #define IDC_STATIC_ALARMOUT_TIME3				IDD_DIALOG_ALARMOUT+15
// #define IDC_STATIC_ALARMOUT_TIME4				IDD_DIALOG_ALARMOUT+16

// #define IDC_CHECK_ALARMOUT_ENABLE1				IDD_DIALOG_ALARMOUT+17
// #define IDC_CHECK_ALARMOUT_ENABLE2				IDD_DIALOG_ALARMOUT+18
// #define IDC_CHECK_ALARMOUT_ENABLE3				IDD_DIALOG_ALARMOUT+19
// #define IDC_CHECK_ALARMOUT_ENABLE4				IDD_DIALOG_ALARMOUT+20

// #define IDC_DATE_ALARMOUT_STIME1				IDD_DIALOG_ALARMOUT+21
// #define IDC_DATE_ALARMOUT_STIME2				IDD_DIALOG_ALARMOUT+22
// #define IDC_DATE_ALARMOUT_STIME3				IDD_DIALOG_ALARMOUT+23
// #define IDC_DATE_ALARMOUT_STIME4				IDD_DIALOG_ALARMOUT+24
// 
// #define IDC_DATE_ALARMOUT_ETIME1				IDD_DIALOG_ALARMOUT+25
// #define IDC_DATE_ALARMOUT_ETIME2				IDD_DIALOG_ALARMOUT+26
// #define IDC_DATE_ALARMOUT_ETIME3				IDD_DIALOG_ALARMOUT+27
// #define IDC_DATE_ALARMOUT_ETIME4				IDD_DIALOG_ALARMOUT+28
//zlb20090915 end
#define IDC_STATIC_ALARMOUT_MAILADDR			IDD_DIALOG_ALARMOUT+29//zlb20090915
#define IDC_EDIT_ALARMOUT_MAILADDR				IDD_DIALOG_ALARMOUT+30//zlb20090915
#define IDC_PROGRESS_ALARMOUT_LINE				IDD_DIALOG_ALARMOUT+31//zlb20090915

//pw 2010/7/14
#define IDC_STATIC_ALARMOUT_MAILSNDADDR			IDD_DIALOG_ALARMOUT+32
#define IDC_EDIT_ALARMOUT_MAILSNDADDR			IDD_DIALOG_ALARMOUT+33
#define IDC_STATIC_ALARMOUT_MAILSNDPWD			IDD_DIALOG_ALARMOUT+34
#define IDC_EDIT_ALARMOUT_MAILSNDPWD			IDD_DIALOG_ALARMOUT+35
#define IDC_STATIC_ALARMOUT_MAIL_SMTP			IDD_DIALOG_ALARMOUT+36
#define IDC_EDIT_ALARMOUT_MAIL_SMTP				IDD_DIALOG_ALARMOUT+37

#ifdef FTP_PIC
#define IDC_PROGRESS_ALARMOUT_LINE2			IDD_DIALOG_ALARMOUT+38
#define IDC_STATIC_ALARMOUT_FTP_IP			IDD_DIALOG_ALARMOUT+39
#define IDC_EDIT_ALARMOUT_FTP_IP			IDD_DIALOG_ALARMOUT+40
#define IDC_STATIC_ALARMOUT_FTP_PORT		IDD_DIALOG_ALARMOUT+41
#define IDC_EDIT_ALARMOUT_FTP_PORT			IDD_DIALOG_ALARMOUT+42
#endif




BOOL CreateAlarmInPage();
BOOL ShowAlarmInPage();
BOOL CreateAlarmOutPage();
BOOL ShowAlarmOutPage();
BOOL CreateSetEMailAddrPage();
BOOL ShowSetEMailAddrPage();
#endif

