#ifndef _CHNSTATEPAGE_H_
#define _CHNSTATEPAGE_H_

#include "ui.h"

#define IDC_STATIC_CHNSTATE_CHNINDEX			IDD_DIALOG_CHNSTATE+1

#define IDC_STATIC_CHNSTATE_CHN1				IDD_DIALOG_CHNSTATE+2
#define IDC_STATIC_CHNSTATE_CHN2				IDD_DIALOG_CHNSTATE+3
#define IDC_STATIC_CHNSTATE_CHN3				IDD_DIALOG_CHNSTATE+4
#define IDC_STATIC_CHNSTATE_CHN4				IDD_DIALOG_CHNSTATE+5
#define IDC_STATIC_CHNSTATE_CHN5				IDD_DIALOG_CHNSTATE+6
#define IDC_STATIC_CHNSTATE_CHN6				IDD_DIALOG_CHNSTATE+7
#define IDC_STATIC_CHNSTATE_CHN7				IDD_DIALOG_CHNSTATE+8
#define IDC_STATIC_CHNSTATE_CHN8				IDD_DIALOG_CHNSTATE+9
#define IDC_STATIC_CHNSTATE_CHN9				IDD_DIALOG_CHNSTATE+10
#define IDC_STATIC_CHNSTATE_CHN10				IDD_DIALOG_CHNSTATE+11
#define IDC_STATIC_CHNSTATE_CHN11				IDD_DIALOG_CHNSTATE+12
#define IDC_STATIC_CHNSTATE_CHN12				IDD_DIALOG_CHNSTATE+13
#define IDC_STATIC_CHNSTATE_CHN13				IDD_DIALOG_CHNSTATE+14
#define IDC_STATIC_CHNSTATE_CHN14				IDD_DIALOG_CHNSTATE+15
#define IDC_STATIC_CHNSTATE_CHN15				IDD_DIALOG_CHNSTATE+16
#define IDC_STATIC_CHNSTATE_CHN16				IDD_DIALOG_CHNSTATE+17


#define IDC_STATIC_CHNSTATE_STATE				IDD_DIALOG_CHNSTATE+18

#define IDC_LIGHT_CHNSTATE_STATE1				IDD_DIALOG_CHNSTATE+19
#define IDC_LIGHT_CHNSTATE_STATE2				IDD_DIALOG_CHNSTATE+20
#define IDC_LIGHT_CHNSTATE_STATE3				IDD_DIALOG_CHNSTATE+21
#define IDC_LIGHT_CHNSTATE_STATE4				IDD_DIALOG_CHNSTATE+22
#define IDC_LIGHT_CHNSTATE_STATE5				IDD_DIALOG_CHNSTATE+23
#define IDC_LIGHT_CHNSTATE_STATE6				IDD_DIALOG_CHNSTATE+24
#define IDC_LIGHT_CHNSTATE_STATE7				IDD_DIALOG_CHNSTATE+25
#define IDC_LIGHT_CHNSTATE_STATE8				IDD_DIALOG_CHNSTATE+26
#define IDC_LIGHT_CHNSTATE_STATE9				IDD_DIALOG_CHNSTATE+27
#define IDC_LIGHT_CHNSTATE_STATE10				IDD_DIALOG_CHNSTATE+28
#define IDC_LIGHT_CHNSTATE_STATE11				IDD_DIALOG_CHNSTATE+29
#define IDC_LIGHT_CHNSTATE_STATE12				IDD_DIALOG_CHNSTATE+30
#define IDC_LIGHT_CHNSTATE_STATE13				IDD_DIALOG_CHNSTATE+31
#define IDC_LIGHT_CHNSTATE_STATE14				IDD_DIALOG_CHNSTATE+32
#define IDC_LIGHT_CHNSTATE_STATE15				IDD_DIALOG_CHNSTATE+33
#define IDC_LIGHT_CHNSTATE_STATE16				IDD_DIALOG_CHNSTATE+34


#define IDC_STATIC_CHNSTATE_ENABLE				IDD_DIALOG_CHNSTATE+35

#define IDC_CHECK_CHNSTATE_ENABLE1				IDD_DIALOG_CHNSTATE+36
#define IDC_CHECK_CHNSTATE_ENABLE2				IDD_DIALOG_CHNSTATE+37
#define IDC_CHECK_CHNSTATE_ENABLE3				IDD_DIALOG_CHNSTATE+38
#define IDC_CHECK_CHNSTATE_ENABLE4				IDD_DIALOG_CHNSTATE+39
#define IDC_CHECK_CHNSTATE_ENABLE5				IDD_DIALOG_CHNSTATE+40
#define IDC_CHECK_CHNSTATE_ENABLE6				IDD_DIALOG_CHNSTATE+41
#define IDC_CHECK_CHNSTATE_ENABLE7				IDD_DIALOG_CHNSTATE+42
#define IDC_CHECK_CHNSTATE_ENABLE8				IDD_DIALOG_CHNSTATE+43
#define IDC_CHECK_CHNSTATE_ENABLE9				IDD_DIALOG_CHNSTATE+44
#define IDC_CHECK_CHNSTATE_ENABLE10				IDD_DIALOG_CHNSTATE+45
#define IDC_CHECK_CHNSTATE_ENABLE11				IDD_DIALOG_CHNSTATE+46
#define IDC_CHECK_CHNSTATE_ENABLE12				IDD_DIALOG_CHNSTATE+47
#define IDC_CHECK_CHNSTATE_ENABLE13				IDD_DIALOG_CHNSTATE+48
#define IDC_CHECK_CHNSTATE_ENABLE14				IDD_DIALOG_CHNSTATE+49
#define IDC_CHECK_CHNSTATE_ENABLE15				IDD_DIALOG_CHNSTATE+50
#define IDC_CHECK_CHNSTATE_ENABLE16				IDD_DIALOG_CHNSTATE+51

#define IDC_BUTTON_CHNSTATE_ALLSTARTUP			IDD_DIALOG_CHNSTATE+52
#define IDC_BUTTON_CHNSTATE_ALLSTOP				IDD_DIALOG_CHNSTATE+53

#define IDC_BUTTON_CHNSTATE_BACK				IDD_DIALOG_CHNSTATE+54

BOOL CreateChnstatePage();
BOOL ShowChnstatePage();

#endif

