#ifndef _DELUSERPAGE_H_
#define _DELUSERPAGE_H_

#include "ui.h"

#define IDC_STATIC_DELUSER_TEXT1		IDD_DIALOG_DELUSER+1
#define IDC_STATIC_DELUSER_TEXT2		IDD_DIALOG_DELUSER+2

#define IDC_BUTTON_DELUSER_OK			IDD_DIALOG_DELUSER+3
#define IDC_BUTTON_DELUSER_CANCEL		IDD_DIALOG_DELUSER+4

BOOL CreateDeluserPage();
BOOL ShowDeluserPage();

#endif
