#ifndef _EDITUSERPAGE_H_
#define _EDITUSERPAGE_H_

#include "ui.h"

#define IDC_STATIC_EDITUSER_USER				IDD_DIALOG_EDITUSER+1

#define IDC_EDIT_EDITUSER_USER					IDD_DIALOG_EDITUSER+4
#define IDC_BUTTON_EDITUSER_PWSET				IDD_DIALOG_EDITUSER+5

#define IDC_STATIC_EDITUSER_TEMPLET				IDD_DIALOG_EDITUSER+7
#define IDC_COMBO_EDITUSER_TEMPLET				IDD_DIALOG_EDITUSER+8
#define IDC_BUTTON_EDITUSER_SELECT				IDD_DIALOG_EDITUSER+9
#define IDC_STATIC_EDITUSER_LOCAL				IDD_DIALOG_EDITUSER+10
#define IDC_CHECK_EDITUSER_LOCALYUNTAI			IDD_DIALOG_EDITUSER+11
#define IDC_CHECK_EDITUSER_LOCALRECORD			IDD_DIALOG_EDITUSER+12
#define IDC_CHECK_EDITUSER_LOCALPLAY			IDD_DIALOG_EDITUSER+13
#define IDC_CHECK_EDITUSER_LOCALSET				IDD_DIALOG_EDITUSER+14
#define IDC_CHECK_EDITUSER_LOCALLOG				IDD_DIALOG_EDITUSER+15
#define IDC_CHECK_EDITUSER_LOCALTOOL			IDD_DIALOG_EDITUSER+16
#define IDC_STATIC_EDITUSER_REMOTE				IDD_DIALOG_EDITUSER+17
#define IDC_CHECK_EDITUSER_REMOTEYUNTAI			IDD_DIALOG_EDITUSER+18
#define IDC_CHECK_EDITUSER_REMOTERECORD			IDD_DIALOG_EDITUSER+19
#define IDC_CHECK_EDITUSER_REMOTEPLAY			IDD_DIALOG_EDITUSER+20
#define IDC_CHECK_EDITUSER_REMOTESET			IDD_DIALOG_EDITUSER+21
#define IDC_CHECK_EDITUSER_REMOTELOG			IDD_DIALOG_EDITUSER+22
#define IDC_CHECK_EDITUSER_REMOTETOOL			IDD_DIALOG_EDITUSER+23
#define IDC_CHECK_EDITUSER_REMOTEPREVIEW		IDD_DIALOG_EDITUSER+24
#define IDC_CHECK_EDITUSER_REMOTEALARM			IDD_DIALOG_EDITUSER+25
#define IDC_CHECK_EDITUSER_REMOTEAUDIO			IDD_DIALOG_EDITUSER+26
#define IDC_STATIC_EDITUSER_PHYSICALADDR		IDD_DIALOG_EDITUSER+27
#define IDC_IPMACADDR_EDITUSER_PHYSICALADDR		IDD_DIALOG_EDITUSER+28
#define IDC_BUTTON_EDITUSER_OK					IDD_DIALOG_EDITUSER+29
#define IDC_BUTTON_EDITUSER_CANCEL				IDD_DIALOG_EDITUSER+30
#define IDC_STATIC_EDITUSER_SHIFTPROMPT_NAME	IDD_DIALOG_EDITUSER+31
#define IDC_STATIC_EDITUSER_SHIFTPROMPT_MAC		IDD_DIALOG_EDITUSER+32
#define IDC_INPUTBOX_EDITUSERT_DENO		IDD_DIALOG_EDITUSER+33
#define IDC_CHECK_EDITUSER_LINE					IDD_DIALOG_EDITUSER+34
#ifdef channel_limit
#define IDC_BUTTON_CHANNEL_LIMIT				IDD_DIALOG_EDITUSER+35  //wangcong
#endif
BOOL CreateEdituserPage();
BOOL ShowEdituserPage();

#if defined(channel_limit)	
#define IDC_STATIC_CHNLIMIT_CHNINDEX 				IDD_DIALOG_CHNLIMIT+1
#define IDC_STATIC_CHNLIMIT_CHN1 					IDD_DIALOG_CHNLIMIT+2
#define IDC_STATIC_CHNLIMIT_CHN2					IDD_DIALOG_CHNLIMIT+3
#define IDC_STATIC_CHNLIMIT_CHN3 					IDD_DIALOG_CHNLIMIT+4
#define IDC_STATIC_CHNLIMIT_CHN4 					IDD_DIALOG_CHNLIMIT+5
#define IDC_STATIC_CHNLIMIT_CHN5 					IDD_DIALOG_CHNLIMIT+6
#define IDC_STATIC_CHNLIMIT_CHN6 					IDD_DIALOG_CHNLIMIT+7
#define IDC_STATIC_CHNLIMIT_CHN7 					IDD_DIALOG_CHNLIMIT+8
#define IDC_STATIC_CHNLIMIT_CHN8 					IDD_DIALOG_CHNLIMIT+9
#define IDC_STATIC_CHNLIMIT_STATE 					IDD_DIALOG_CHNLIMIT+10
#define IDC_CHECK_CHNLIMIT_ENABLE1 				IDD_DIALOG_CHNLIMIT+1
#define IDC_CHECK_CHNLIMIT_ENABLE2				IDD_DIALOG_CHNLIMIT+12
#define IDC_CHECK_CHNLIMIT_ENABLE3 				IDD_DIALOG_CHNLIMIT+13
#define IDC_CHECK_CHNLIMIT_ENABLE4 				IDD_DIALOG_CHNLIMIT+14
#define IDC_CHECK_CHNLIMIT_ENABLE5 				IDD_DIALOG_CHNLIMIT+15
#define IDC_CHECK_CHNLIMIT_ENABLE6 				IDD_DIALOG_CHNLIMIT+16
#define IDC_CHECK_CHNLIMIT_ENABLE7 				IDD_DIALOG_CHNLIMIT+17
#define IDC_CHECK_CHNLIMIT_ENABLE8 				IDD_DIALOG_CHNLIMIT+18
#define IDC_BUTTON_CHNLIMIT_ALLSTART			IDD_DIALOG_CHNLIMIT+19
#define IDC_BUTTON_CHNLIMIT_ALLSTOP			IDD_DIALOG_CHNLIMIT+20
#define IDC_BUTTON_CHNLIMIT_BACK				IDD_DIALOG_CHNLIMIT+21
BOOL CreateChnlimitPage();
BOOL ShowChnlimitPage();
#endif
#endif
