#ifndef _FORMAT_H_
#define _FORMAT_H_

#include "ui.h"

#define IDC_STATIC_FORMAT_TEXT1		IDD_DIALOG_FORMAT+1
#define IDC_STATIC_FORMAT_TEXT2		IDD_DIALOG_FORMAT+2
#define IDC_BUTTON_FORMAT_OK		IDD_DIALOG_FORMAT+3
#define IDC_BUTTON_FORMAT_CANCEL	IDD_DIALOG_FORMAT+4

#define  IDC_STATIC_HDDFORMATPROG_TEXT   	IDD_DIALOG_HDDFORMATPROG+1
#define  IDC_PROGRESS_HDDFORMATPROG    		IDD_DIALOG_HDDFORMATPROG+2
#define  IDC_STATIC_HDDFORMATVALUE_TEXT    	IDD_DIALOG_HDDFORMATPROG+3

BOOL CreateFormatPage();
BOOL ShowFormatPage();

BOOL CreateFormatProgPage();
BOOL ShowFormatProgPage();
#endif
