#ifndef _HDDPAGE_H_
#define _HDDPAGE_H_

#include "ui.h"

#define IDC_STATIC_HDD_SELECT			IDD_DIALOG_HDD+1
#define IDC_COMBO_HDD_SELECT			IDD_DIALOG_HDD+2
#define IDC_STATIC_HDD_CONTENT			IDD_DIALOG_HDD+3
#define IDC_STATIC_HDD_REMAIN			IDD_DIALOG_HDD+4
#define IDC_STATIC_HDD_SLEEP			IDD_DIALOG_HDD+5
#define IDC_STATIC_HDD_STATE			IDD_DIALOG_HDD+6
#define IDC_STATIC_HDD_INFO				IDD_DIALOG_HDD+7
#define IDC_STATIC_HDD_CONTENT_VALUE	IDD_DIALOG_HDD+8
#define IDC_STATIC_HDD_REMAIN_VALUE		IDD_DIALOG_HDD+9
#define IDC_STATIC_HDD_SLEEP_VALUE		IDD_DIALOG_HDD+10
#define IDC_STATIC_HDD_STATE_VALUE		IDD_DIALOG_HDD+11
#define IDC_BUTTON_HDD_FORMAT			IDD_DIALOG_HDD+12
#define IDC_BUTTON_HDD_CANCEL			IDD_DIALOG_HDD+13
#define IDC_STATIC_HDD_STAT_INFO		IDD_DIALOG_HDD+18
#define IDC_STATIC_HDD_STAT_INFO2		IDD_DIALOG_HDD+19
#define IDC_STATIC_HDD_ACT		IDD_DIALOG_HDD+20
#define IDC_COMBO_HDD_ACT		IDD_DIALOG_HDD+21

//pw 2010/9/27
#define IDC_BUTTON_HDD_OK									IDD_DIALOG_HDD+22
#define IDC_STATIC_SYSTEMPARAM_24						IDD_DIALOG_HDD+23
#define IDC_CHECK_SYSTEMPARAM_24							IDD_DIALOG_HDD+24
 #define IDC_STATIC_SYSTEMPARAM_REWRITERECORD			IDD_DIALOG_HDD+25
#define IDC_CHECK_SYSTEMPARAM_REWRITRECORD				IDD_DIALOG_HDD+26
#define IDC_STATIC_SYSTEMPARAM_DAYS						IDD_DIALOG_HDD+27


#ifdef SHOW_DISK_PROGRSS
#define IDD_DIALOG_HDDPROG		IDD_DIALOG_HDD+40
#define IDC_STATIC_HDDPROG_TEXT		IDD_DIALOG_HDD+41
#define IDC_PROGRESS_HDDPROG		IDD_DIALOG_HDD+42
#define IDC_PROGRESS_HDDPROGVALUE_TEXT		IDD_DIALOG_HDD+43
#endif


/*******************/
//07-12-13
#define IDC_STATIC_HDD_FORMAT			IDD_DIALOG_HDD+14
#define IDC_STATIC_HDD_FORMAT_VALUE		IDD_DIALOG_HDD+15

#define IDC_COMBO_HDD_SELECT_MASTER  IDD_DIALOG_HDD+16
#define IDC_COMBO_HDD_SELECT_SLAVE  IDD_DIALOG_HDD+17

BOOL CreateHddPage();
BOOL ShowHddPage();
BOOL CreateHddProgPage();

#endif
