#ifndef _IMAGEDETECTTIMEPAGE_H_
#define _IMAGEDETECTTIMEPAGE_H_

#include "ui.h"

#define IDC_STATIC_IMAGEDETECTTIME_DATE						IDD_DIALOG_IMAGEDETECTTIME+1
#define IDC_COMBO_IMAGEDETECTTIME_DATE						IDD_DIALOG_IMAGEDETECTTIME+2

#define IDC_STATIC_IMAGEDETECTTIME_WHOLEDAY					IDD_DIALOG_IMAGEDETECTTIME+3
#define IDC_CHECK_IMAGEDETECTTIME_WHOLEDAY					IDD_DIALOG_IMAGEDETECTTIME+4

#define IDC_STATIC_IMAGEDETECTTIME_TIMESECTION1				IDD_DIALOG_IMAGEDETECTTIME+5
#define IDC_EDIT_IMAGEDETECTTIME_STARTTIME1					IDD_DIALOG_IMAGEDETECTTIME+6
#define IDC_EDIT_IMAGEDETECTTIME_ENDTIME1					IDD_DIALOG_IMAGEDETECTTIME+7

#define IDC_STATIC_IMAGEDETECTTIME_TIMESECTION2				IDD_DIALOG_IMAGEDETECTTIME+8
#define IDC_EDIT_IMAGEDETECTTIME_STARTTIME2					IDD_DIALOG_IMAGEDETECTTIME+9
#define IDC_EDIT_IMAGEDETECTTIME_ENDTIME2					IDD_DIALOG_IMAGEDETECTTIME+10

#define IDC_STATIC_IMAGEDETECTTIME_TIMESECTION3				IDD_DIALOG_IMAGEDETECTTIME+11
#define IDC_EDIT_IMAGEDETECTTIME_STARTTIME3					IDD_DIALOG_IMAGEDETECTTIME+12
#define IDC_EDIT_IMAGEDETECTTIME_ENDTIME3					IDD_DIALOG_IMAGEDETECTTIME+13

#define IDC_STATIC_IMAGEDETECTTIME_TIMESECTION4				IDD_DIALOG_IMAGEDETECTTIME+14
#define IDC_EDIT_IMAGEDETECTTIME_STARTTIME4					IDD_DIALOG_IMAGEDETECTTIME+15
#define IDC_EDIT_IMAGEDETECTTIME_ENDTIME4					IDD_DIALOG_IMAGEDETECTTIME+16

#define IDC_STATIC_IMAGEDETECTTIME_COPY						IDD_DIALOG_IMAGEDETECTTIME+17
#define IDC_COMBO_IMAGEDETECTTIME_COPY						IDD_DIALOG_IMAGEDETECTTIME+18
#define IDC_BUTTON_IMAGEDETECTTIME_COPY						IDD_DIALOG_IMAGEDETECTTIME+19

#define IDC_BUTTON_IMAGEDETECTTIME_OK						IDD_DIALOG_IMAGEDETECTTIME+20
#define IDC_BUTTON_IMAGEDETECTTIME_CANCEL					IDD_DIALOG_IMAGEDETECTTIME+21

#define IDC_COMBO_IMAGEDETECTTIME_TIMETYPE					IDD_DIALOG_IMAGEDETECTTIME+22
#define IDC_CHECK_IMAGEDETECTTIME_TIMESECTION1                       IDD_DIALOG_IMAGEDETECTTIME+23
#define IDC_DATETIME_IMAGEDETECTTIME_STARTTIME1                     IDD_DIALOG_IMAGEDETECTTIME+24
#define IDC_DATETIME_IMAGEDETECTTIME_ENDTIME1                         IDD_DIALOG_IMAGEDETECTTIME+25
#define IDC_CHECK_IMAGEDETECTTIME_TIMESECTION2                       IDD_DIALOG_IMAGEDETECTTIME+26
#define IDC_DATETIME_IMAGEDETECTTIME_STARTTIME2                     IDD_DIALOG_IMAGEDETECTTIME+27
#define IDC_DATETIME_IMAGEDETECTTIME_ENDTIME2                         IDD_DIALOG_IMAGEDETECTTIME+28
#define IDC_CHECK_IMAGEDETECTTIME_TIMESECTION3                       IDD_DIALOG_IMAGEDETECTTIME+29
#define IDC_DATETIME_IMAGEDETECTTIME_STARTTIME3                     IDD_DIALOG_IMAGEDETECTTIME+30
#define IDC_DATETIME_IMAGEDETECTTIME_ENDTIME3                         IDD_DIALOG_IMAGEDETECTTIME+31
#define IDC_CHECK_IMAGEDETECTTIME_TIMESECTION4                       IDD_DIALOG_IMAGEDETECTTIME+32
#define IDC_DATETIME_IMAGEDETECTTIME_STARTTIME4                     IDD_DIALOG_IMAGEDETECTTIME+33
#define IDC_DATETIME_IMAGEDETECTTIME_ENDTIME4                         IDD_DIALOG_IMAGEDETECTTIME+34

#define IDC_CHECK_IMAGEDETECTTIME_COPY0                                          IDD_DIALOG_IMAGEDETECTTIME+35
#define IDC_CHECK_IMAGEDETECTTIME_COPY1                                          IDD_DIALOG_IMAGEDETECTTIME+36
#define IDC_CHECK_IMAGEDETECTTIME_COPY2                                          IDD_DIALOG_IMAGEDETECTTIME+37
#define IDC_CHECK_IMAGEDETECTTIME_COPY3                                          IDD_DIALOG_IMAGEDETECTTIME+38
#define IDC_CHECK_IMAGEDETECTTIME_COPY4                                          IDD_DIALOG_IMAGEDETECTTIME+39
#define IDC_CHECK_IMAGEDETECTTIME_COPY5                                          IDD_DIALOG_IMAGEDETECTTIME+40
#define IDC_CHECK_IMAGEDETECTTIME_COPY6                                          IDD_DIALOG_IMAGEDETECTTIME+41

#define IDC_CHECK_IMAGEDETECTTIME_COPYOTHER                                 IDD_DIALOG_IMAGEDETECTTIME+42
#define IDC_INPUTBOX_IMAGEDETECTTIME_DENO                                 IDD_DIALOG_IMAGEDETECTTIME+43


BOOL CreateImagedetecttimePage();
BOOL ShowImagedetecttimePage();

void GetImageTimeFlagAndChn(u8 *pflag,u8 *pchn);
void SetImageTimeFlagAndChn(u8 flag,u8 chn);

#endif
