#ifndef _MAINTAIN_H_
#define _MAINTAIN_H_

#include "ui.h"

#define IDC_BUTTON_MAINTAINTIME_OK		  		IDD_DIALOG_MAINTAIN+1
#define IDC_BUTTON_MAINTAINTIME_CANCEL			IDD_DIALOG_MAINTAIN+2
#define IDC_EDIT_MAINTAIN_DAYBLANK				IDD_DIALOG_MAINTAIN+3
#define IDC_STATIC_MAINTAIN_TYPEBLANK			IDD_DIALOG_MAINTAIN+4
#define IDC_DATETIME_MAINTAIN_TIME				IDD_DIALOG_MAINTAIN+5
#define IDC_CHECK_MAINTAIN_USESHOW			IDD_DIALOG_MAINTAIN+6
#define IDC_COMBO_MAINTAIN_TYPE					IDD_DIALOG_MAINTAIN+7
#define IDC_COMBO_MAINTAIN_WEEK					IDD_DIALOG_MAINTAIN+8
#define IDC_COMBO_MAINTAIN_START				IDD_DIALOG_MAINTAIN+9
#define IDC_STATIC_MAINTAIN_TIMEBLANK			IDD_DIALOG_MAINTAIN+10
#define IDC_STATIC_MAINTAIN_USEBLANK			IDD_DIALOG_MAINTAIN+11

BOOL CreateMainTainPage();
BOOL ShowMainTainPage();

#endif
