#ifndef _ONLINEPAGE_H_
#define _ONLINEPAGE_H_

#include "ui.h"

#define IDC_STATIC_ONLINE_INDEX			IDD_DIALOG_ONLINE+1
#define IDC_STATIC_ONLINE_USER			IDD_DIALOG_ONLINE+2
#define IDC_STATIC_ONLINE_IP			IDD_DIALOG_ONLINE+3

#define IDC_LIST_ONLINE_USERINFO		IDD_DIALOG_ONLINE+4
#define IDC_BUTTON_ONLINE_DISCONNECT	IDD_DIALOG_ONLINE+5
#define IDC_BUTTON_ONLINE_BACK			IDD_DIALOG_ONLINE+6

BOOL CreateOnlinePage();
BOOL ShowOnlinePage();

#endif
