#ifndef _SETPASSWDPAGE_H_
#define _SETPASSWDPAGE_H_

#include "ui.h"

#define IDC_STATIC_PASSWDSET_NEW		IDD_DIALOG_PASSWDSET+1
#define IDC_STATIC_PASSWDSET_SURE		IDD_DIALOG_PASSWDSET+2  

#define IDC_EDIT_PASSWDSET_NEW			IDD_DIALOG_PASSWDSET+3
#define IDC_EDIT_PASSWDSET_SURE			IDD_DIALOG_PASSWDSET+4

#define IDC_BUTTON_PASSWDSET_OK			IDD_DIALOG_PASSWDSET+5
#define IDC_BUTTON_PASSWDSET_CANCEL		IDD_DIALOG_PASSWDSET+6


#define IDC_INPUTBOX_PASSWDSET_DENO		IDD_DIALOG_PASSWDSET+7
#define IDC_EDIT_PASSWDSET_NEW2			IDD_DIALOG_PASSWDSET+8
#define IDC_EDIT_PASSWDSET_SURE2			IDD_DIALOG_PASSWDSET+9
#define IDC_INPUTBOX_PASSWDSET_DENO2		IDD_DIALOG_PASSWDSET+10
#define IDC_BUTTON_PASSWDSET_OK2			IDD_DIALOG_PASSWDSET+11

BOOL CreatePasswdSetPage();
BOOL ShowPasswdSetPage();
BOOL CreatePasswdSetPage2();
BOOL ShowPasswdSetPage2();

void OnPasswdSetOK(Wnd* pWnd,Message_event event,s32 param);
void OnPasswdSetCancel(Wnd* pWnd,Message_event event,s32 param);

#endif

