#ifndef _PLAYPAGE_H_
#define _PLAYPAGE_H_

#include "ui.h"

#ifdef _NVR_
#define IDC_STATIC_IPNC_IP			IDD_DIALOG_IPNC+1
#define IDC_STATIC_IPNC_MAC			IDD_DIALOG_IPNC+2
#define IDC_STATIC_IPNC_NAME		IDD_DIALOG_IPNC+3
#define IDC_LIST_IPNC_INFO			IDD_DIALOG_IPNC+4
#define IDC_BUTTON_IPNC_SEARCH		IDD_DIALOG_IPNC+5
#define IDC_BUTTON_IPNC_SET			IDD_DIALOG_IPNC+6
#define IDC_STATIC_IPNC_LINK		IDD_DIALOG_IPNC+7
#define IDC_COMBO_IPNC_LINK			IDD_DIALOG_IPNC+8
#define IDC_BUTTON_IPNC_SURE		IDD_DIALOG_IPNC+9
#define IDC_BUTTON_IPNC_CHNINFO		IDD_DIALOG_IPNC+10
#define IDC_STATIC_IPNC_SELECT		IDD_DIALOG_IPNC+11
#define IDC_STATIC_IPNC_CHNNO		IDD_DIALOG_IPNC+12

#define IDC_STATIC_NVRCHN_IP		IDD_DIALOG_NVRCHN+1
#define IDC_STATIC_NVRCHN_MAC		IDD_DIALOG_NVRCHN+2
#define IDC_STATIC_NVRCHN_NAME		IDD_DIALOG_NVRCHN+3
#define IDC_STATIC_NVRCHN_CHNNO		IDD_DIALOG_NVRCHN+4
#define IDC_STATIC_NVRCHN_ONLINE	IDD_DIALOG_NVRCHN+5
#define IDC_LIST_NVRCHN_INFO		IDD_DIALOG_NVRCHN+6
#define IDC_STATIC_NVRCHN_DELLINK	IDD_DIALOG_NVRCHN+7
#define IDC_COMBO_NVRCHN_DELLINK	IDD_DIALOG_NVRCHN+8
#define IDC_BUTTON_NVRCHN_SURE		IDD_DIALOG_NVRCHN+9
#define IDC_STATIC_NVRCHN_CAMERA	IDD_DIALOG_NVRCHN+10
#define IDC_IPMAC_NVRCHN_CAMERA		IDD_DIALOG_NVRCHN+11
#define IDC_STATIC_NVRCHN_ADDTOCHN	IDD_DIALOG_NVRCHN+12
#define IDC_COMBO_NVRCHN_ADDTOCHN	IDD_DIALOG_NVRCHN+13
#define IDC_BUTTON_NVRCHN_ADDSURE	IDD_DIALOG_NVRCHN+14

#define IDC_STATIC_IPNCNET_CAMERA	IDD_DIALOG_IPNCNET+1
#define IDC_STATIC_IPNCNET_IP		IDD_DIALOG_IPNCNET+2
#define IDC_STATIC_IPNCNET_NEWIP	IDD_DIALOG_IPNCNET+3
#define IDC_IPMAC_IPNCNET_NEWIP		IDD_DIALOG_IPNCNET+4
#define IDC_STATIC_IPNCNET_NEWMASK	IDD_DIALOG_IPNCNET+5
#define IDC_IPMAC_IPNCNET_NEWMASK	IDD_DIALOG_IPNCNET+6
#define IDC_STATIC_IPNCNET_NEWGATE	IDD_DIALOG_IPNCNET+7
#define IDC_IPMAC_IPNCNET_NEWGATE	IDD_DIALOG_IPNCNET+8
#define IDC_STATIC_IPNCNET_NEWDNS	IDD_DIALOG_IPNCNET+9
#define IDC_IPMAC_IPNCNET_NEWDNS	IDD_DIALOG_IPNCNET+10

#define IDC_STATIC_IPNCNET_USER		IDD_DIALOG_IPNCNET+11
#define IDC_EDIT_IPNCNET_USER		IDD_DIALOG_IPNCNET+12
#define IDC_STATIC_IPNCNET_PASSWD	IDD_DIALOG_IPNCNET+13
#define IDC_EDIT_IPNCNET_PASSWD		IDD_DIALOG_IPNCNET+14

#define IDC_BUTTON_IPNCNET_OK		IDD_DIALOG_IPNCNET+15
#define IDC_BUTTON_IPNCNET_CANCEL	IDD_DIALOG_IPNCNET+16

BOOL CreateIPNCPage();
BOOL CreateNVRCHNPage();
BOOL CreateIPNCNetPage();
#endif

#define PIC_PLAYING_PLAY     	"data/pics/play.png"
#define PIC_PLAYING_FAST     	"data/pics/fast.png"
#define PIC_PLAYING_PAUSE    	"data/pics/pause.png"
#define PIC_PLAYING_STOP     	"data/pics/stop.png"
#define PIC_PLAYING_SLOW     	"data/pics/slow.png"
#define PIC_PLAYING_MUTE     	"data/pics/voice.png"
#define PIC_PLAYING_PREV     	"data/pics/prev.png"
#define PIC_PLAYING_NEXT		"data/pics/next.png"
#define PIC_PLAYING_VOICE   	"data/pics/voice.png"
#define PIC_PLAYING_SINGLE  	"data/pics/single.png"
#define PIC_PLAYING_PREV1   	"data/pics/prev1.png"
#define PIC_PLAYING_NEXT1		"data/pics/next1.png"

#define IDC_STATIC_PLAY_CHNINDEX			IDD_DIALOG_PLAY+1
#define IDC_COMBO_SEARCH_STORE				IDD_DIALOG_PLAY+2

#define IDC_STATIC_PLAY_RECORDTYPE			IDD_DIALOG_PLAY+3
#define IDC_COMBO_PLAY_RECORDTYPE			IDD_DIALOG_PLAY+4
#define IDC_STATIC_PLAY_RECORDTIME			IDD_DIALOG_PLAY+5
#define IDC_STATIC_PLAY_TO					IDD_DIALOG_PLAY+8

#define IDC_BUTTON_PLAY_SEARCH			IDD_DIALOG_PLAY+11
#define IDC_BUTTON_PLAY_PLAY				IDD_DIALOG_PLAY+12

#define IDC_STATIC_PLAY_SELECTPAGE			IDD_DIALOG_PLAY+13
#define IDC_EDIT_PLAY_CURPAGE				IDD_DIALOG_PLAY+14
#define IDC_STATIC_PLAY_COMPART				IDD_DIALOG_PLAY+15
#define IDC_STATIC_PLAY_TOTALPAGE			IDD_DIALOG_PLAY+16

#define IDC_STATIC_PLAY_FILEINDEX			IDD_DIALOG_PLAY+17
#define IDC_STATIC_PLAY_FILETIME			IDD_DIALOG_PLAY+18
#define IDC_STATIC_PLAY_FILESIZE			IDD_DIALOG_PLAY+19
#define IDC_STATIC_PLAY_FILEFLAG			IDD_DIALOG_PLAY+20
#define IDC_LIST_PLAY_FILEINFO				IDD_DIALOG_PLAY+21

#define IDC_STATIC_PLAY_STORE				IDD_DIALOG_PLAY+22
#define IDC_COMBO_PLAY_STORE				IDD_DIALOG_PLAY+23

#define IDC_BUTTON_PLAY_BACKUP				IDD_DIALOG_PLAY+24

#define IDC_BUTTON_PLAY_COPY				IDD_DIALOG_PLAY+25
#define IDC_BUTTON_PLAY_HIT					IDD_DIALOG_PLAY+26
#define IDC_BUTTON_PLAY_NOTHIT				IDD_DIALOG_PLAY+27

//#define IDC_BUTTON_PLAY_BACK				IDD_DIALOG_PLAY+28

#define IDC_EDIT_PLAY_STARTYEAR				IDD_DIALOG_PLAY+29
#define IDC_EDIT_PLAY_STARTMON				IDD_DIALOG_PLAY+30
#define IDC_EDIT_PLAY_STARTDAY				IDD_DIALOG_PLAY+31
#define IDC_EDIT_PLAY_STARTHOUR				IDD_DIALOG_PLAY+32
#define IDC_EDIT_PLAY_STARTMIN				IDD_DIALOG_PLAY+33
#define IDC_EDIT_PLAY_STARTSEC				IDD_DIALOG_PLAY+34

#define IDC_EDIT_PLAY_ENDYEAR				IDD_DIALOG_PLAY+35
#define IDC_EDIT_PLAY_ENDMON				IDD_DIALOG_PLAY+36
#define IDC_EDIT_PLAY_ENDDAY				IDD_DIALOG_PLAY+37
#define IDC_EDIT_PLAY_ENDHOUR				IDD_DIALOG_PLAY+38
#define IDC_EDIT_PLAY_ENDMIN				IDD_DIALOG_PLAY+39
#define IDC_EDIT_PLAY_ENDSEC				IDD_DIALOG_PLAY+40

#define IDC_STATIC_PLAY_STARTSEP1			IDD_DIALOG_PLAY+41
#define IDC_STATIC_PLAY_STARTSEP2			IDD_DIALOG_PLAY+42
#define IDC_STATIC_PLAY_STARTSEP3			IDD_DIALOG_PLAY+43
#define IDC_STATIC_PLAY_STARTSEP4			IDD_DIALOG_PLAY+44

#define IDC_STATIC_PLAY_ENDSEP1				IDD_DIALOG_PLAY+45
#define IDC_STATIC_PLAY_ENDSEP2				IDD_DIALOG_PLAY+46
#define IDC_STATIC_PLAY_ENDSEP3				IDD_DIALOG_PLAY+47
#define IDC_STATIC_PLAY_ENDSEP4				IDD_DIALOG_PLAY+48

#define IDC_DATETIME_PLAY_STARTTIME			IDD_DIALOG_PLAY+49
#define IDC_DATETIME_PLAY_ENDTIME			IDD_DIALOG_PLAY+50

#define IDC_BUTTON_PLAY_GOTOPAGE			IDD_DIALOG_PLAY+51 
#define IDC_STATIC_PLAY_SHOW1				IDD_DIALOG_PLAY+52
#define IDC_STATIC_PLAY_SHOW2				IDD_DIALOG_PLAY+52+4
#define IDC_STATIC_PLAY_SHOW3				IDD_DIALOG_PLAY+52+5
#define IDC_STATIC_PLAY_SHOW4				IDD_DIALOG_PLAY+52+6



#define IDC_CHECK_PLAY_CH1	IDD_DIALOG_PLAY+59

#define IDC_CHECK_REC_TYPE1	IDD_DIALOG_PLAY+59+16
#define IDC_CHECK_REC_TYPE2	IDD_DIALOG_PLAY+59+16+1
#define IDC_CHECK_REC_TYPE3	IDD_DIALOG_PLAY+59+16+2
#define IDC_CHECK_REC_TYPE4	IDD_DIALOG_PLAY+59+16+3

#define IDC_BUTTON_PLAY_CANCEL IDD_DIALOG_PLAY+59+16+4



#define IDC_STATIC_PLAY_CHNO	IDD_DIALOG_SEARCH_RESULT+5
#define IDC_STATIC_SEARCH_INFO  IDD_DIALOG_SEARCH_RESULT+6
#define IDC_BUTTON_SEARCH_BACKUP  IDD_DIALOG_SEARCH_RESULT+7
#define IDC_BUTTON_SEARCH_PLAY  IDD_DIALOG_SEARCH_RESULT+8


#define IDC_BUTTON_PLAY_NEXT	IDD_DIALOG_SEARCH_RESULT+9
#define IDC_BUTTON_PLAY_PRE	IDD_DIALOG_SEARCH_RESULT+10

#define IDC_STATIC_SEARCH_INFO_END_TIME  IDD_DIALOG_SEARCH_RESULT+11
#define IDC_STATIC_SEARCH_INFO_END_TIME_TXT  IDD_DIALOG_SEARCH_RESULT+12
#define IDC_STATIC_SEARCH_INFO_TIME  IDD_DIALOG_SEARCH_RESULT+13
#define IDC_STATIC_SEARCH_INFO_TIME_TXT IDD_DIALOG_SEARCH_RESULT+14


#define IDC_STATIC_PLAY_LOADFILE			IDD_DIALOG_PLAY_LOADFILE+1


/***********************/
//07-08-21
#define IDC_STATIC_BACKUP_TO				IDD_DIALOG_PLAY+53
#define IDC_DATETIME_BACKUP_STARTTIME		IDD_DIALOG_PLAY+54
#define IDC_DATETIME_BACKUP_ENDTIME			IDD_DIALOG_PLAY+55
#define IDC_INPUTBOX_PLAY_DENO				IDD_DIALOG_PLAY+58

#define IDD_DIALOG_PLAY_INFO				IDD_DIALOG_PLAY+99

#ifdef BACKUP_AS_AVI
#define IDC_STATIC_BACKUPFORMAT_TEXT		IDD_DIALOG_BACKUPFORMAT+1
#define IDC_BUTTON_BACKUPFORMAT_IFV			IDD_DIALOG_BACKUPFORMAT+2
#define IDC_BUTTON_BACKUPFORMAT_AVI			IDD_DIALOG_BACKUPFORMAT+3
#endif

#define IDC_STATIC_BACKUPPROG_TEXT  		IDD_DIALOG_BACKUPPROG+1
#define IDC_PROGRESS_BACKUP    				IDD_DIALOG_BACKUPPROG+2
#define IDC_BUTTON_BACKUPPROG_CANCEL        IDD_DIALOG_BACKUPPROG+3
#define IDC_STATIC_BACKUPVALUE_TEXT       	IDD_DIALOG_BACKUPPROG+4
//pw
#define IDC_BUTTON_BACKUPPROG_NO			IDD_DIALOG_BACKUPPROG+5


#define IDC_PICTURE_PLAYING_PLAY			IDD_DIALOG_PLAY_PLAYING+1
#define IDC_PICTURE_PLAYING_FAST			IDD_DIALOG_PLAY_PLAYING+2
#define IDC_PICTURE_PLAYING_PAUSE			IDD_DIALOG_PLAY_PLAYING+3
#define IDC_PICTURE_PLAYING_STOP			IDD_DIALOG_PLAY_PLAYING+4
#define IDC_PICTURE_PLAYING_SLOW			IDD_DIALOG_PLAY_PLAYING+5
#define IDC_PICTURE_PLAYING_MUTE			IDD_DIALOG_PLAY_PLAYING+6
#define IDC_PICTURE_PLAYING_PREV			IDD_DIALOG_PLAY_PLAYING+7
#define IDC_PICTURE_PLAYING_NEXT			IDD_DIALOG_PLAY_PLAYING+8
#define IDC_PICTURE_PLAYING_STEP			IDD_DIALOG_PLAY_PLAYING+9
#define IDC_STATIC_PLAYING_INF_RATE			IDD_DIALOG_PLAY_PLAYING+10
#define IDC_STATIC_PLAYING_INF_RATIO		IDD_DIALOG_PLAY_PLAYING+11
#define IDC_STATIC_PLAYING_INF_HOURS		IDD_DIALOG_PLAY_PLAYING+12
#define IDC_STATIC_PLAYING_INF_MINUTES		IDD_DIALOG_PLAY_PLAYING+13
#define IDC_STATIC_PLAYING_INF_SECONDS		IDD_DIALOG_PLAY_PLAYING+14
#define IDC_STATIC_PLAYING_INF_TOTALTIME	IDD_DIALOG_PLAY_PLAYING+15

#define IDC_SLIDER_PLAYING_PROGRESS			IDD_DIALOG_PLAY_PLAYING+16

#define IDC_CHECK_PLAY_BAKUP_CHNALL	 		IDD_DIALOG_PLAY_BAKUP_CHN+1
#define IDC_CHECK_PLAY_BAKUP_CHN1	 		IDD_DIALOG_PLAY_BAKUP_CHN+2
#define IDC_CHECK_PLAY_BAKUP_CHN2			IDD_DIALOG_PLAY_BAKUP_CHN+3
#define IDC_CHECK_PLAY_BAKUP_CHN3 			IDD_DIALOG_PLAY_BAKUP_CHN+4
#define IDC_CHECK_PLAY_BAKUP_CHN4 			IDD_DIALOG_PLAY_BAKUP_CHN+5
#define IDC_BUTTON_PLAY_BAKUP_COPY 			IDD_DIALOG_PLAY_BAKUP_CHN+6
#define IDC_STATIC_PLAY_BAKUP_CHOICE 		IDD_DIALOG_PLAY_BAKUP_CHN+7

#define IDC_CHECK_PLAY_CDRECORD_Z			IDD_DIALOG_PLAY_CDRECORD+1
#define IDC_CHECK_PLAY_CDRECORD_M		 	IDD_DIALOG_PLAY_CDRECORD+2
#define IDC_BUTTON_PLAY_CDRECORD_COPY		IDD_DIALOG_PLAY_CDRECORD+3
#define IDC_STATIC_PLAY_CDRECORD	 		IDD_DIALOG_PLAY_CDRECORD+4
#define IDC_BUTTON_PLAY_CDRECORD_CANCEL	IDD_DIALOG_PLAY_CDRECORD+5

void GetCdrFlag(u8 *pflag);
void SetCdrFlag(u8 flag);

#define IDC_STATIC_PLAYTIME_CHOICE			IDD_DIALOG_PLAYTIME_CHN+1
#define IDC_CHECK_PLAYTIME_CHN1				IDD_DIALOG_PLAYTIME_CHN+2
#define IDC_CHECK_PLAYTIME_CHN2				IDD_DIALOG_PLAYTIME_CHN+3
#define IDC_CHECK_PLAYTIME_CHN3				IDD_DIALOG_PLAYTIME_CHN+4
#define IDC_CHECK_PLAYTIME_CHN4				IDD_DIALOG_PLAYTIME_CHN+5
#define IDC_BUTTON_PLAYTIME_ALL				IDD_DIALOG_PLAYTIME_CHN+6

#define IDC_STATIC_PLAYTIME_ERROR				IDD_DIALOG_PLAYTIME_CHN+7


BOOL CreatePlayPage();
BOOL ShowPlayPage();

BOOL CreateBackupProgPage();
BOOL ShowBackupProgPage();


BOOL CreateLoadfilePage();
BOOL ShowLoadfilePage();


BOOL CreatePlayingPage();
BOOL ShowPlayingPage();

BOOL CreatePlayBakupChnPage();
BOOL CreateCdrecordPage();
BOOL CreatePlaytimeChnPage();
BOOL CreateSearchResultPage();

#ifdef BACKUP_AS_AVI
BOOL CreateBackupFormatPage();
#endif

#endif

