#ifndef _SCHEDULE_H_
#define _SCHEDULE_H_

#include "ui.h"

#define IDC_STATIC_SCHEDULE_CH			IDD_DIALOG_SCHEDULE+1

#define IDC_COMBO_SCHEDULE_CHINDEX			IDD_DIALOG_SCHEDULE+2
#define IDC_STATIC_SCHEDULE_PRERECORD			IDD_DIALOG_SCHEDULE+3
#define IDC_CHECK_SCHEDULE_PRERECORD				IDD_DIALOG_SCHEDULE+4

#define IDC_STATIC_SCHEDULE_WEEK				IDD_DIALOG_SCHEDULE+5
#define IDC_COMBO_SCHEDULE_WEEK			IDD_DIALOG_SCHEDULE+6

#define IDC_STATIC_SCHEDULE_TIME1				IDD_DIALOG_SCHEDULE+7

#define IDC_CHECK_SCHEDULE_REC1				IDD_DIALOG_SCHEDULE+8
#define IDC_CHECK_SCHEDULE_REC2				IDD_DIALOG_SCHEDULE+9
#define IDC_CHECK_SCHEDULE_REC3				IDD_DIALOG_SCHEDULE+10
#define IDC_CHECK_SCHEDULE_REC4				IDD_DIALOG_SCHEDULE+11

#define IDC_CHECK_SCHEDULE_MTD1	IDD_DIALOG_SCHEDULE+12
#define IDC_CHECK_SCHEDULE_MTD2	IDD_DIALOG_SCHEDULE+13
#define IDC_CHECK_SCHEDULE_MTD3	IDD_DIALOG_SCHEDULE+14
#define IDC_CHECK_SCHEDULE_MTD4	IDD_DIALOG_SCHEDULE+15

#define IDC_CHECK_SCHEDULE_ALARM1	IDD_DIALOG_SCHEDULE+16
#define IDC_CHECK_SCHEDULE_ALARM2	IDD_DIALOG_SCHEDULE+17
#define IDC_CHECK_SCHEDULE_ALARM3	IDD_DIALOG_SCHEDULE+18
#define IDC_CHECK_SCHEDULE_ALARM4	IDD_DIALOG_SCHEDULE+19

#define IDC_STATIC_SCHEDULE_RECTYPE	IDD_DIALOG_SCHEDULE+20
#define IDC_STATIC_SCHEDULE_SCHREC	IDD_DIALOG_SCHEDULE+21
#define IDC_STATIC_SCHEDULE_MTDREC	IDD_DIALOG_SCHEDULE+22
#define IDC_STATIC_SCHEDULE_ALARMREC	IDD_DIALOG_SCHEDULE+23
#define IDC_STATIC_SCHEDULE_SCHREC2	IDD_DIALOG_SCHEDULE+24
#define IDC_STATIC_SCHEDULE_MTDREC2	IDD_DIALOG_SCHEDULE+25
#define IDC_STATIC_SCHEDULE_ALARMREC2	IDD_DIALOG_SCHEDULE+26

#define IDC_DATE_SCHEDULE_STIME1				IDD_DIALOG_SCHEDULE+27
#define IDC_DATE_SCHEDULE_STIME2				IDD_DIALOG_SCHEDULE+28
#define IDC_DATE_SCHEDULE_STIME3				IDD_DIALOG_SCHEDULE+29
#define IDC_DATE_SCHEDULE_STIME4				IDD_DIALOG_SCHEDULE+30



#define IDC_DATE_SCHEDULE_ETIME1				IDD_DIALOG_SCHEDULE+31
#define IDC_DATE_SCHEDULE_ETIME2				IDD_DIALOG_SCHEDULE+32
#define IDC_DATE_SCHEDULE_ETIME3				IDD_DIALOG_SCHEDULE+33
#define IDC_DATE_SCHEDULE_ETIME4				IDD_DIALOG_SCHEDULE+34

#define IDC_STATIC_SCHEDULE_TIME3				IDD_DIALOG_SCHEDULE+35


#define IDC_STATIC_SCHEDULE_TIME2				IDD_DIALOG_SCHEDULE+36
#define IDC_STATIC_SCHEDULE_TIME4				IDD_DIALOG_SCHEDULE+37



#define IDC_BUTTON_SCHEDULE_OK				IDD_DIALOG_SCHEDULE+38
#define IDC_BUTTON_SCHEDULE_CANCEL			IDD_DIALOG_SCHEDULE+39
#define IDC_BUTTON_SCHEDULE_COPY				IDD_DIALOG_SCHEDULE+40
#define IDC_COMBO_SCHEDULE_COPY				IDD_DIALOG_SCHEDULE+41

#define IDC_STATIC_SCHEDULE_TIMESTR0			IDD_DIALOG_SCHEDULE+42
#define IDC_STATIC_SCHEDULE_TIMESTR6			IDD_DIALOG_SCHEDULE+43
#define IDC_STATIC_SCHEDULE_TIMESTR12		IDD_DIALOG_SCHEDULE+44
#define IDC_STATIC_SCHEDULE_TIMESTR18		IDD_DIALOG_SCHEDULE+45
#define IDC_STATIC_SCHEDULE_TIMESTR24		IDD_DIALOG_SCHEDULE+46

#define IDC_STATIC_SCHEDULE_TIMELINE1			IDD_DIALOG_SCHEDULE+47
#define IDC_STATIC_SCHEDULE_TIMELINE2			IDD_DIALOG_SCHEDULE+48
#define IDC_STATIC_SCHEDULE_TIMELINE3			IDD_DIALOG_SCHEDULE+49
#define IDC_STATIC_SCHEDULE_TIMELINE4			IDD_DIALOG_SCHEDULE+50
#define IDC_STATIC_SCHEDULE_TIMELINE5			IDD_DIALOG_SCHEDULE+51
#define IDC_STATIC_SCHEDULE_TIMELINE6			IDD_DIALOG_SCHEDULE+52

#define IDC_STATIC_ALARMSCH_WEEK				IDD_DIALOG_ALARMSCH+1
#define IDC_COMBO_ALARMSCH_WEEK					IDD_DIALOG_ALARMSCH+2

#define IDC_STATIC_ALARMSCH_TIME1				IDD_DIALOG_ALARMSCH+3
#define IDC_STATIC_ALARMSCH_TIME2				IDD_DIALOG_ALARMSCH+4
#define IDC_STATIC_ALARMSCH_TIME3				IDD_DIALOG_ALARMSCH+5
#define IDC_STATIC_ALARMSCH_TIME4				IDD_DIALOG_ALARMSCH+6

#define IDC_CHECK_ALARMSCH_ENABLE1				IDD_DIALOG_ALARMSCH+7
#define IDC_CHECK_ALARMSCH_ENABLE2				IDD_DIALOG_ALARMSCH+8
#define IDC_CHECK_ALARMSCH_ENABLE3				IDD_DIALOG_ALARMSCH+9
#define IDC_CHECK_ALARMSCH_ENABLE4				IDD_DIALOG_ALARMSCH+10

#define IDC_DATE_ALARMSCH_STIME1				IDD_DIALOG_ALARMSCH+11
#define IDC_DATE_ALARMSCH_STIME2				IDD_DIALOG_ALARMSCH+12
#define IDC_DATE_ALARMSCH_STIME3				IDD_DIALOG_ALARMSCH+13
#define IDC_DATE_ALARMSCH_STIME4				IDD_DIALOG_ALARMSCH+14

#define IDC_DATE_ALARMSCH_ETIME1				IDD_DIALOG_ALARMSCH+15
#define IDC_DATE_ALARMSCH_ETIME2				IDD_DIALOG_ALARMSCH+16
#define IDC_DATE_ALARMSCH_ETIME3				IDD_DIALOG_ALARMSCH+17
#define IDC_DATE_ALARMSCH_ETIME4				IDD_DIALOG_ALARMSCH+18

#define IDC_BUTTON_ALARMSCH_OK					IDD_DIALOG_ALARMSCH+19
#define IDC_BUTTON_ALARMSCH_CANCEL				IDD_DIALOG_ALARMSCH+20

#define IDC_STATIC_ALARMSCH_TIMESTR0			IDD_DIALOG_ALARMSCH+21
#define IDC_STATIC_ALARMSCH_TIMESTR6			IDD_DIALOG_ALARMSCH+22
#define IDC_STATIC_ALARMSCH_TIMESTR12			IDD_DIALOG_ALARMSCH+23
#define IDC_STATIC_ALARMSCH_TIMESTR18			IDD_DIALOG_ALARMSCH+24
#define IDC_STATIC_ALARMSCH_TIMESTR24			IDD_DIALOG_ALARMSCH+25

#define IDC_STATIC_ALARMSCH_TIMELINE1			IDD_DIALOG_ALARMSCH+26
#define IDC_STATIC_ALARMSCH_TIMELINE2			IDD_DIALOG_ALARMSCH+27
#define IDC_STATIC_ALARMSCH_TIMELINE3			IDD_DIALOG_ALARMSCH+28
#define IDC_STATIC_ALARMSCH_TIMELINE4			IDD_DIALOG_ALARMSCH+29

#define IDC_STATIC_ALARMSCH_CH				IDD_DIALOG_ALARMSCH+30
#define IDC_COMBO_ALARMSCH_CHINDEX			IDD_DIALOG_ALARMSCH+31

#define IDC_BUTTON_ALARMSCH_COPY				IDD_DIALOG_ALARMSCH+32
#define IDC_COMBO_ALARMSCH_COPY				IDD_DIALOG_ALARMSCH+33

#define IDC_STATIC_ALARMSCH_TYPE			IDD_DIALOG_ALARMSCH+34
#define IDC_COMBO_ALARMSCH_TYPE				IDD_DIALOG_ALARMSCH+35
#define IDC_STATIC_MDSCH_CH			IDD_DIALOG_ALARMSCH+36

BOOL CreateSchedulePage();
BOOL ShowSchedulePage();
void draw_total_schedule_view();

#ifdef ALARMSCH
BOOL CreateAlarmSchedulePage();
BOOL ShowAlarmSchedulePage();
void draw_total_alarm_schedule_view();
#endif
#endif
