#ifndef _SYSDATETIMEPAGE_H_
#define _SYSDATETIMEPAGE_H_

#include "ui.h"

#define IDC_STATIC_SYSDATETIME_DATE				IDD_DIALOG_SYSDATETIME+1
#define IDC_STATIC_SYSDATETIME_TIME				IDD_DIALOG_SYSDATETIME+2  

#define IDC_DATETIME_SYSDATETIME_DATE			IDD_DIALOG_SYSDATETIME+3
#define IDC_DATETIME_SYSDATETIME_TIME		 	IDD_DIALOG_SYSDATETIME+4

#define IDC_BUTTON_SYSDATETIME_OK		  		IDD_DIALOG_SYSDATETIME+5
#define IDC_BUTTON_SYSDATETIME_CANCEL			IDD_DIALOG_SYSDATETIME+6
#define IDC_INPUTBOX_SYSDATETIME_DENO			IDD_DIALOG_SYSDATETIME+7

#define IDC_STATIC_SYSDATETIME_FORMAT			IDD_DIALOG_SYSDATETIME+8
#define IDC_COMBOBOX_SYSDATETIME_FORMAT			IDD_DIALOG_SYSDATETIME+9

//pw 2010/6/23
#define 	IDC_STATIC_SYSDATETIME_NTP				IDD_DIALOG_SYSDATETIME+10
#define	IDC_STATIC_SYSDATETIME_NTP_SERVER		IDD_DIALOG_SYSDATETIME+11
#define	IDC_STATIC_SYSDATETIME_NTP_TIMEZONE	IDD_DIALOG_SYSDATETIME+12
#define IDC_CHECKBOX_SYSDATETIME_NTP				IDD_DIALOG_SYSDATETIME+13
#define IDC_EDITBOX_SYSDATETIME_NTP_SERVERIP	IDD_DIALOG_SYSDATETIME+14
#define IDC_COMBOBOX_SYSDATETIME_NTP_TIMEZONE	IDD_DIALOG_SYSDATETIME+15
#define IDC_COMBOBOX_SYSDATETIME_NTP_TZNUM		IDD_DIALOG_SYSDATETIME+16
#define IDC_BUTTON_SYSDATETIME_DST				IDD_DIALOG_SYSDATETIME+17
#ifdef _DAYTIME_
#define IDC_STATIC_SYSDATETIME_NTP_DST				IDD_DIALOG_SYSDATETIME+18
#endif


//pw 2010/6/24
#define	IDC_STATIC_DST								IDD_DIALOG_DST+1
#define	IDC_STATIC_DST_BEGIN_DATE				IDD_DIALOG_DST+2
#define	IDC_STATIC_DST_END_DATE					IDD_DIALOG_DST+3

#define	IDC_CHECKBOX_DST_VALUE					IDD_DIALOG_DST+4
#define	IDC_DST_BEGIN_DATE						IDD_DIALOG_DST+5
#define	IDC_DST_END_DATE							IDD_DIALOG_DST+6

#define	IDC_BUTTON_DST_OK		  				IDD_DIALOG_DST+7
#define	IDC_BUTTON_DST_CANCEL					IDD_DIALOG_DST+8


BOOL CreateSysDateTimePage();
BOOL ShowSysDateTimePage();

void OnSysDateTimeOK(Wnd *pWnd,Message_event msg_ev,s32 param);
void OnSysDateTimeCancel(Wnd *pWnd,Message_event msg_ev,s32 param);

//pw 2010/6/24

BOOL CreateDSTPage();
BOOL ShowDSTPage();

void OnDSTOK(Wnd *pWnd,Message_event msg_ev,s32 param);
void OnDSTCancel(Wnd *pWnd,Message_event msg_ev,s32 param);

#endif

