#ifndef _SYSTEMPARAMPAGE_H_
#define _SYSTEMPARAMPAGE_H_

#include "ui.h"

#define IDC_STATIC_SYSTEMPARAM_DEVICEID			IDD_DIALOG_SYSTEMPARAM+1
#define IDC_STATIC_SYSTEMPARAM_DEVICENAME		IDD_DIALOG_SYSTEMPARAM+2
#define IDC_STATIC_SYSTEMPARAM_DISKFULL			IDD_DIALOG_SYSTEMPARAM+3
#define IDC_STATIC_SYSTEMPARAM_KEYBOARDLOCKTIME IDD_DIALOG_SYSTEMPARAM+6
#define IDC_STATIC_SYSTEMPARAM_SWITCHTIME		IDD_DIALOG_SYSTEMPARAM+7
#define IDC_STATIC_SYSTEMPARAM_STATESHOW		IDD_DIALOG_SYSTEMPARAM+8
#define IDC_STATIC_SYSTEMPARAM_VIDEOFORMAT		IDD_DIALOG_SYSTEMPARAM+9
#define IDC_STATIC_SYSTEMPARAM_VGARESOUTION		IDD_DIALOG_SYSTEMPARAM+10

#define IDC_EDIT_SYSTEMPARAM_DEVICEID			IDD_DIALOG_SYSTEMPARAM+11
#define IDC_EDIT_SYSTEMPARAM_DEVICENAME			IDD_DIALOG_SYSTEMPARAM+12
#define IDC_COMBO_SYSTEMPARAM_DISKFULL			IDD_DIALOG_SYSTEMPARAM+13
#define IDC_COMBO_SYSTEMPARAM_KEYBOARDLOCKTIME	IDD_DIALOG_SYSTEMPARAM+16
#define IDC_COMBO_SYSTEMPARAM_SWITCHTIME		IDD_DIALOG_SYSTEMPARAM+17
#define IDC_CHECK_SYSTEMPARAM_STATESHOW			IDD_DIALOG_SYSTEMPARAM+18
#define IDC_COMBO_SYSTEMPARAM_VIDEOFORMAT		IDD_DIALOG_SYSTEMPARAM+19
#define IDC_COMBO_SYSTEMPARAM_VGARESOUTION		IDD_DIALOG_SYSTEMPARAM+20

#define IDC_BUTTON_SYSTEMPARAM_OK				IDD_DIALOG_SYSTEMPARAM+21
#define IDC_BUTTON_SYSTEMPARAM_CANCEL			IDD_DIALOG_SYSTEMPARAM+22

#define IDC_STATIC_SYSTEMPARAM_TRANSPARENCY		IDD_DIALOG_SYSTEMPARAM+23
#define IDC_STATIC_SYSTEMPARAM_LANGUAGE			IDD_DIALOG_SYSTEMPARAM+24

#define IDC_COMBO_SYSTEMPARAM_TRANSPARENCY		IDD_DIALOG_SYSTEMPARAM+25
#define IDC_COMBO_SYSTEMPARAM_LANGUAGE			IDD_DIALOG_SYSTEMPARAM+26
#define IDC_STATIC_SYSTEMPARAM_WATERMARK		IDD_DIALOG_SYSTEMPARAM+27
#define IDC_COMBO_SYSTEMPARAM_WATERMARK			IDD_DIALOG_SYSTEMPARAM+28

#define IDC_STATIC_SYSTEMPARAM_SHIFTPROMPT		IDD_DIALOG_SYSTEMPARAM+29
#define IDC_INPUTBOX_ISYSTEMPARAM_DENO			IDD_DIALOG_SYSTEMPARAM+30
#define IDC_STATIC_SYSTEMPARAM_NOTPASSWD		IDD_DIALOG_SYSTEMPARAM+31
#define IDC_COMBO_SYSTEMPARAM_NOTPASSWD			IDD_DIALOG_SYSTEMPARAM+32

BOOL CreateSystemParamPage();
BOOL ShowSystemParamPage();

void OnSystemParamOK(Wnd *pWnd,Message_event msg_ev,s32 param);
int getOsdValue(int param);
void OnSystemParamCancel(Wnd *pWnd,Message_event msg_ev,s32 param);

#endif

