#ifndef _UPDATEPAGE_H_
#define _UPDATEPAGE_H_

#include "ui.h"

#define IDC_STATIC_UPDATE_WAY		IDD_DIALOG_UPDATE+1
#define IDC_STATIC_UPDATE_SERVIP	IDD_DIALOG_UPDATE+2

#define IDC_COMBO_UPDATE_WAY		IDD_DIALOG_UPDATE+3
#define IDC_EDIT_UPDATE_SERVIP		IDD_DIALOG_UPDATE+4

#define IDC_BUTTON_UPDATE_OK		IDD_DIALOG_UPDATE+5
#define IDC_BUTTON_UPDATE_CANCEL	IDD_DIALOG_UPDATE+6

#define IDC_IPMACADDR_UPDATE_SERVIP IDD_DIALOG_UPDATE+7

//07-11-06
#define IDC_STATIC_UPDATE_TYPE 		IDD_DIALOG_UPDATE+8
#define IDC_COMBO_UPDATE_TYPE		IDD_DIALOG_UPDATE+9
#define IDC_INPUTBOX_UPDATE_DENO		IDD_DIALOG_UPDATE+10

//pw 2010/9/10
#define IDC_COMBO_UPDATE_WAY_USB_ONLY	IDD_DIALOG_UPDATE+12

BOOL CreateUpdatePage();
BOOL ShowUpdatePage();

#define IDC_STATIC_UPDATESUCC_TEXT	IDD_DIALOG_UPDATESUCC+1
#define IDC_BUTTON_UPDATESUCC_OK	IDD_DIALOG_UPDATESUCC+2	
#define IDC_STATIC_UPDATEPROG_TEXT  IDD_DIALOG_UPDATEPROG+1
//#define IDC_STATIC_UPDATEPROG_TEXTING  IDD_DIALOG_UPDATEPROG+2
#define IDC_PROGRESS_UPDATE     IDD_DIALOG_UPDATEPROG+3
#define IDC_STATIC_UPDATEVALUE_TEXT   IDD_DIALOG_UPDATEPROG+4

BOOL CreateUpdateSuccPage();
BOOL ShowUpdateSuccPage();
BOOL CreateUpdateProgPage();
BOOL ShowUpdateProgPage();

#endif
