#ifndef _USERMANAGEPAGE_H_
#define _USERMANAGEPAGE_H_

#include "ui.h"

#define IDC_STATIC_USERMANAGE_INDEX			IDD_DIALOG_USERMANAGE+1
#define IDC_STATIC_USERMANAGE_USER			IDD_DIALOG_USERMANAGE+2
#define IDC_LIST_USERMANAGE_USERINFO		IDD_DIALOG_USERMANAGE+3
#define IDC_BUTTON_USERMANAGE_ADD			IDD_DIALOG_USERMANAGE+4
#define IDC_BUTTON_USERMANAGE_MODIFY		IDD_DIALOG_USERMANAGE+5
#define IDC_BUTTON_USERMANAGE_DEL			IDD_DIALOG_USERMANAGE+6
#define IDC_BUTTON_USERMANAGE_BACK			IDD_DIALOG_USERMANAGE+7
#define IDC_BUTTON_USERMANAGE_PREPAGE		IDD_DIALOG_USERMANAGE+8
#define IDC_BUTTON_USERMANAGE_NEXTPAGE		IDD_DIALOG_USERMANAGE+9
#define IDC_BUTTON_USERMANAGE_FIRSTPAGE		IDD_DIALOG_USERMANAGE+10
#define IDC_BUTTON_USERMANAGE_ENDPAGE		IDD_DIALOG_USERMANAGE+11

//07-10-30
#define IDC_STATIC_USERMANAGE_SELECTPAGE	IDD_DIALOG_USERMANAGE+12
#define IDC_EDIT_USERMANAGE_SELECTPAGE		IDD_DIALOG_USERMANAGE+13
#define IDC_STATIC_USERMANAGE_COMPART		IDD_DIALOG_USERMANAGE+14
#define IDC_STATIC_USERMANAGE_TOTALPAGE		IDD_DIALOG_USERMANAGE+15
#define IDC_BUTTON_USERMANAGE_GOTOPAGE		IDD_DIALOG_USERMANAGE+16
#define IDC_INPUTBOX_USERMANAGEG_DENO		IDD_DIALOG_USERMANAGE+17
//cyl added
#define IDC_STATIC_USERMANAGE_INFO			IDD_DIALOG_USERMANAGE+18
//07-10-30

BOOL CreateUsermanagePage();
BOOL ShowUsermanagePage();

#endif

