#ifndef _YUNTAITRACKPAGE_H_
#define _YUNTAITRACKPAGE_H_

#include "ui.h"

#define IDC_BUTTON_YTTRACK_STARTPATTERN		IDD_DIALOG_YTTRACK+1
#define IDC_BUTTON_YTTRACK_STARTRUN			IDD_DIALOG_YTTRACK+2

#define IDC_PIC_YTTRACK_LEFT				IDD_DIALOG_YTTRACK+3
#define IDC_PIC_YTTRACK_RIGHT			IDD_DIALOG_YTTRACK+4
#define IDC_PIC_YTTRACK_UP				IDD_DIALOG_YTTRACK+5
#define IDC_PIC_YTTRACK_DOWN				IDD_DIALOG_YTTRACK+6

#define IDC_BUTTON_YTTRACK_ZOOMDOWN			IDD_DIALOG_YTTRACK+7
#define IDC_BUTTON_YTTRACK_ZOOMUP			IDD_DIALOG_YTTRACK+8
#define IDC_BUTTON_YTTRACK_IRISDOWN			IDD_DIALOG_YTTRACK+9
#define IDC_BUTTON_YTTRACK_IRISUP			IDD_DIALOG_YTTRACK+10
#define IDC_BUTTON_YTTRACK_FOCUSDOWN		IDD_DIALOG_YTTRACK+11
#define IDC_BUTTON_YTTRACK_FOCUSUP			IDD_DIALOG_YTTRACK+12
#define IDC_BUTTON_YTTRACK_STOPPATTERN		IDD_DIALOG_YTTRACK+13
#define IDC_BUTTON_YTTRACK_CANCEL			IDD_DIALOG_YTTRACK+14
#define IDC_BUTTON_YTTRACK_STOP				IDD_DIALOG_YTTRACK+15 //comment  by lshu 20070429

BOOL CreateYunTaiTrackPage();
BOOL ShowYunTaiTrackPage();

#endif
