#ifndef _YUNTAIPAGE_H_
#define _YUNTAIPAGE_H_

#include "ui.h"

#define IDC_STATIC_YUNTAI_CHNINDEX			IDD_DIALOG_YUNTAI+1
#define IDC_STATIC_YUNTAI_BITRATE			IDD_DIALOG_YUNTAI+2
#define IDC_STATIC_YUNTAI_DATEBIT			IDD_DIALOG_YUNTAI+3
#define IDC_STATIC_YUNTAI_STOPBIT			IDD_DIALOG_YUNTAI+4
#define IDC_STATIC_YUNTAI_VERIFYBIT			IDD_DIALOG_YUNTAI+5
#define IDC_STATIC_YUNTAI_STREAMCONTROL		IDD_DIALOG_YUNTAI+6
#define IDC_STATIC_YUNTAI_PROTOCOLTYPE		IDD_DIALOG_YUNTAI+7
#define IDC_STATIC_YUNTAI_DECODERADDR		IDD_DIALOG_YUNTAI+8
#define IDC_STATIC_YUNTAI_PRESETPOS			IDD_DIALOG_YUNTAI+9
#define IDC_STATIC_YUNTAI_CRUISE			IDD_DIALOG_YUNTAI+10
#define IDC_STATIC_YUNTAI_TRACK				IDD_DIALOG_YUNTAI+11

#define IDC_COMBO_YUNTAI_CHNINDEX			IDD_DIALOG_YUNTAI+12
#define IDC_COMBO_YUNTAI_BITRATE			IDD_DIALOG_YUNTAI+13
#define IDC_COMBO_YUNTAI_DATEBIT			IDD_DIALOG_YUNTAI+14
#define IDC_COMBO_YUNTAI_STOPBIT			IDD_DIALOG_YUNTAI+15
#define IDC_COMBO_YUNTAI_VERIFYBIT			IDD_DIALOG_YUNTAI+16
#define IDC_COMBO_YUNTAI_STREAMCONTROL		IDD_DIALOG_YUNTAI+17
#define IDC_COMBO_YUNTAI_PROTOCOLTYPE		IDD_DIALOG_YUNTAI+18
#define IDC_EDIT_YUNTAI_DECODERADDR			IDD_DIALOG_YUNTAI+19
#define IDC_BUTTON_YUNTAI_PRESETPOS			IDD_DIALOG_YUNTAI+20
#define IDC_BUTTON_YUNTAI_CRUISE			IDD_DIALOG_YUNTAI+21
#define IDC_BUTTON_YUNTAI_TRACK				IDD_DIALOG_YUNTAI+22

#define IDC_STATIC_YUNTAI_COPY				IDD_DIALOG_YUNTAI+23
#define IDC_COMBO_YUNTAI_COPY				IDD_DIALOG_YUNTAI+24
#define IDC_BUTTON_YUNTAI_COPY				IDD_DIALOG_YUNTAI+25

#define IDC_BUTTON_YUNTAI_OK				IDD_DIALOG_YUNTAI+26
#define IDC_BUTTON_YUNTAI_CANCEL			IDD_DIALOG_YUNTAI+27
#define IDC_INPUTBOX_YUNTAI_DENO			IDD_DIALOG_YUNTAI+28

BOOL CreateYuntaiPage();
BOOL ShowYuntaiPage();

#endif
