#ifndef _YUNTAICONTROLPAGE_H_
#define _YUNTAICONTROLPAGE_H_

#include "ui.h"
/* move to uicommon.h
#define PIC_YUNTAICTRL_MOVE_UP     "data/pics/up.png"
#define PIC_YUNTAICTRL_MOVE_DOWN    "data/pics/down.png"
#define PIC_YUNTAICTRL_MOVE_LEFT     "data/pics/left.png"
#define PIC_YUNTAICTRL_MOVE_RIGHT    "data/pics/right.png"
*/


#define  PIC_MOVE_AUTO	"data/pics/auto.png"
#define  PIC_MOVE_AUTO_STOP	"data/pics/auto_stop.png"
#define  PIC_ADD	"data/pics/add.png"
#define  PIC_SUB	"data/pics/sub.png"


#define IDC_COMBO_YUNTAICTRLCHN			IDD_DIALOG_YUNTAICTRL+1
#define IDC_INPUTBOX_YUNTAICTRL			IDD_DIALOG_YUNTAICTRL+2


#define IDC_STATIC_YUNTAICTRLMOVE1			IDD_DIALOG_YUNTAICTRLMOVE+1
#define IDC_STATIC_YUNTAICTRLMOVE2			IDD_DIALOG_YUNTAICTRLMOVE+2
#define IDC_PICTURE_YUNTAICTRL_MOVE_UP         IDD_DIALOG_YUNTAICTRLMOVE+3
#define IDC_PICTURE_YUNTAICTRL_MOVE_DOWN          IDD_DIALOG_YUNTAICTRLMOVE+4
#define IDC_PICTURE_YUNTAICTRL_MOVE_LEFT          IDD_DIALOG_YUNTAICTRLMOVE+5
#define IDC_PICTURE_YUNTAICTRL_MOVE_RIGHT          IDD_DIALOG_YUNTAICTRLMOVE+6
#define IDC_BUTTON_YUNTAICTRL_MOVE_AUROSCANSTART         IDD_DIALOG_YUNTAICTRLMOVE+7
#define IDC_BUTTON_YUNTAICTRL_MOVE_AUTOSCANSTOP          IDD_DIALOG_YUNTAICTRLMOVE+8

#define IDC_STATIC_YUNTAICTRLZOOM			IDD_DIALOG_YUNTAICTRLZOOM+1
#define IDC_BUTTON_YUNTAICTRLZOOM_IN			IDD_DIALOG_YUNTAICTRLZOOM+2
#define IDC_BUTTON_YUNTAICTRLZOOM_OUT			IDD_DIALOG_YUNTAICTRLZOOM+3



#define IDC_STATIC_YUNTAICTRLFOCUS			IDD_DIALOG_YUNTAICTRLFOCUS+1
#define IDC_BUTTON_YUNTAICTRLFOCUS_UP			IDD_DIALOG_YUNTAICTRLFOCUS+2
#define IDC_BUTTON_YUNTAICTRLFOCUS_DOWN			IDD_DIALOG_YUNTAICTRLFOCUS+3


#define IDC_STATIC_YUNTAICTRLIRIS			IDD_DIALOG_YUNTAICTRLIRIS+1
#define IDC_BUTTON_YUNTAICTRLIRIS_IN			IDD_DIALOG_YUNTAICTRLIRIS+2
#define IDC_BUTTON_YUNTAICTRLIRIS_OUT			IDD_DIALOG_YUNTAICTRLIRIS+3


#define IDC_STATIC_YUNTAICTRLWIPER			IDD_DIALOG_YUNTAICTRLWIPER+1
#define IDC_BUTTON_YUNTAICTRLWIPER_OPEN			IDD_DIALOG_YUNTAICTRLWIPER+2
#define IDC_BUTTON_YUNTAICTRLWIPER_CLOSE			IDD_DIALOG_YUNTAICTRLWIPER+3


#define IDC_STATIC_YUNTAICTRLLIGHT			IDD_DIALOG_YUNTAICTRLLIGHT+1
#define IDC_BUTTON_YUNTAICTRLLIGHT_OPEN			IDD_DIALOG_YUNTAICTRLLIGHT+2
#define IDC_BUTTON_YUNTAICTRLLIGHT_CLOSE			IDD_DIALOG_YUNTAICTRLLIGHT+3


#define IDC_STATIC_YUNTAICTRLAUX		IDD_DIALOG_YUNTAICTRLAUX+1
#define IDC_EDITBOX_YUNTAICTRLAUX			IDD_DIALOG_YUNTAICTRLAUX+2
#define IDC_BUTTON_YUNTAICTRLAUX_OPEN			IDD_DIALOG_YUNTAICTRLAUX+3
#define IDC_BUTTON_YUNTAICTRLAUX_CLOSE		IDD_DIALOG_YUNTAICTRLAUX+4

#define IDC_STATIC_YUNTAICTRLPRESET			IDD_DIALOG_YUNTAICTRLPRESET+1
#define IDC_EDITBOX_YUNTAICTRLPRESET		IDD_DIALOG_YUNTAICTRLPRESET+2
#define IDC_BUTTON_YUNTAICTRLPRESET_OK	IDD_DIALOG_YUNTAICTRLPRESET+3

#define IDC_STATIC_YUNTAICTRLCRUISE		IDD_DIALOG_YUNTAICTRLCRUISE+1
#define IDC_EDITBOX_YUNTAICTRLCRUISE		IDD_DIALOG_YUNTAICTRLCRUISE+2
#define IDC_BUTTON_YUNTAICTRLCRUISE_START		IDD_DIALOG_YUNTAICTRLCRUISE+3
#define IDC_BUTTON_YUNTAICTRLCRUISE_END		IDD_DIALOG_YUNTAICTRLCRUISE+4

#define IDC_COMBO_YUNTAICTRL_MOVE          IDD_DIALOG_YUNTAICTRLBASE+200
#define IDC_COMBO_YUNTAICTRL_ZOOM          IDD_DIALOG_YUNTAICTRLBASE+201
#define IDC_COMBO_YUNTAICTRL_FOCUS          IDD_DIALOG_YUNTAICTRLBASE+202
#define IDC_COMBO_YUNTAICTRL_IRIS          IDD_DIALOG_YUNTAICTRLBASE+203
#define IDC_COMBO_YUNTAICTRL_WIPER          IDD_DIALOG_YUNTAICTRLBASE+204
#define IDC_COMBO_YUNTAICTRL_LIGHT         IDD_DIALOG_YUNTAICTRLBASE+205
#define IDC_COMBO_YUNTAICTRL_AUX          IDD_DIALOG_YUNTAICTRLBASE+206
#define IDC_COMBO_YUNTAICTRL_PRESET          IDD_DIALOG_YUNTAICTRLBASE+207
#define IDC_COMBO_YUNTAICTRL_CRUISE          IDD_DIALOG_YUNTAICTRLBASE+208
#define IDC_COMBO_YUNTAICTRL          IDD_DIALOG_YUNTAICTRLBASE+213
#define IDC_BUTTON_YUNTAICTRL_SWITCH	 IDD_DIALOG_YUNTAICTRLBASE+214
#define IDC_PIC_YUNTAICTRL_MOVE_AUROSCANSTART IDD_DIALOG_YUNTAICTRLBASE+215
#define IDC_PIC_YUNTAICTRL_MOVE_AUTOSCANSTOP IDD_DIALOG_YUNTAICTRLBASE+216

#define IDC_TEXT_YUNTAICTRLZOOM IDD_DIALOG_YUNTAICTRLBASE+217
#define IDC_TEXT_YUNTAICTRLFOCUS IDD_DIALOG_YUNTAICTRLBASE+218
#define IDC_TEXT_YUNTAICTRLIRIS IDD_DIALOG_YUNTAICTRLBASE+219
#define IDC_CHECK_YUNTAICTRLLIGHT_OPEN IDD_DIALOG_YUNTAICTRLBASE+220
#define IDC_CHECK_YUNTAICTRLWIPER_OPEN IDD_DIALOG_YUNTAICTRLBASE+221
#define IDC_TEXT_YUNTAICTRLLIGHT_OPEN	IDD_DIALOG_YUNTAICTRLBASE+222
#define IDC_TEXT_YUNTAICTRLWIPER_OPEN	IDD_DIALOG_YUNTAICTRLBASE+223
#define IDC_COMBO_YUNTAICTRLSPEED	IDD_DIALOG_YUNTAICTRLBASE+224

BOOL CreateYunTaiControlPage();
BOOL ShowYunTaiControlPage();
/*
BOOL CreateYunTaiControlMovePage();
BOOL ShowYunTaiControlMovePage();

BOOL CreateYunTaiControlZoomPage();
BOOL ShowYunTaiControlZoomPage();

BOOL CreateYunTaiControlFocusPage();
BOOL ShowYunTaiControlFocusPage();

BOOL CreateYunTaiControlIrisPage();
BOOL ShowYunTaiControlIrisPage();

BOOL CreateYunTaiControlWiperPage();
BOOL ShowYunTaiControlWiperPage();

BOOL CreateYunTaiControlLightPage();
BOOL ShowYunTaiControlLightPage();

BOOL CreateYunTaiControlAuxPage();
BOOL ShowYunTaiControlAuxPage();

BOOL CreateYunTaiControlPresetPage();
BOOL ShowYunTaiControlPresetPage();

BOOL CreateYunTaiControlCruisePage();
BOOL ShowYunTaiControlCruisePage();
*/
#endif
