#ifndef _USER_CONFIG_H_
#define _USER_CONFIG_H_

//system
#define CONFIG_SYSTEM_PARAM					"System"
#define CONFIG_SYSTEM_PARAM_DEVNAME			"DevName"
#define CONFIG_SYSTEM_PARAM_DEVID			"DevId"
#define CONFIG_SYSTEM_PARAM_MANUAL	   	 	"Manual"
#define CONFIG_SYSTEM_PARAM_VIDEOSTAND		"VideoStandard"
#define CONFIG_SYSTEM_PARAM_AUTHCHECK		"AuthCheck"
#define CONFIG_SYSTEM_PARAM_OUTPUT			"Output"
#define CONFIG_SYSTEM_PARAM_LANGID			"LangId"
#define CONFIG_SYSTEM_PARAM_SHOWGUIDE		"ShowGuide"
#define CONFIG_SYSTEM_PARAM_LOCKTIME		"LockTime"
#define CONFIG_SYSTEM_PARAM_DATEFORMAT		"DateFormat"
#define CONFIG_SYSTEM_PARAM_TIMESTAND		"TimeStandard"
#define CONFIG_SYSTEM_PARAM_CIRCLEREC		"CyclingRecord"
#define CONFIG_SYSTEM_PARAM_SHOWFIRSTMENUE	"ShowFirstMenue"
#define CONFIG_SYSTEM_PARAM_SN				"SN"//csp modify
#define CONFIG_SYSTEM_PARAM_SyscCheck		"SyscCheck"//QYJ
#define CONFIG_SYSTEM_PARAM_NtpServerAdress	"NtpServerAdress"//QYJ
#define CONFIG_SYSTEM_PARAM_TimeZone		"TimeZone"//QYJ
#define CONFIG_SYSTEM_PARAM_SyncTimeToIPC	"SyncTimeToIPC"
#define CONFIG_SYSTEM_PARAM_P2PEnable		"P2PEnable"

//MainTain
#define CONFIG_MAINTAIN_PARAM				"MainTain"
#define	EM_CONFIG_MAINTAIN_PARAM_ENABLE 	"MainTainEnable"
#define	EM_CONFIG_MAINTAIN_PARAM_MAINTYPE	"MainTainMainType"
#define	EM_CONFIG_MAINTAIN_PARAM_SUBTYPE	"MainTainSubType"
#define	EM_CONFIG_MAINTAIN_PARAM_TIME		"MainTainTime"

//preview
#define CONFIG_PREVIEW_PARAM					"Preview"
#define CONFIG_PREVIEW_PARAM_MODE				"Mode"
#define CONFIG_PREVIEW_PARAM_MODEPARA			"ModePara"
#define CONFIG_PREVIEW_PARAM_AUDIOOUTCHN		"AudioOutChn"
#define CONFIG_PREVIEW_PARAM_VOLUME				"Volume"
#define CONFIG_PREVIEW_PARAM_MUTE				"Mute"
#define CONFIG_PREVIEW_PARAM_ISPATROL			"IsPatrol"
#define CONFIG_PREVIEW_PARAM_INTERVAL			"Interval"
#define CONFIG_PREVIEW_PARAM_PATROLMODE			"PatrolMode"
#define CONFIG_PREVIEW_PARAM_STOPS				"Stops"
#define CONFIG_PREVIEW_PARAM_STOPMODEPARA		"StopModePara"
#define CONFIG_PREVIEW_PARAM_PREVIEWCOLOR		"PreviewColor"
#define CONFIG_PREVIEW_PARAM_PLAYBACKCOLOR		"PlayBackColor"
#define CONFIG_PREVIEW_PARAM_VIDEOSRCTYPEPARA	"VideoSrcType"

enum
{
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_HUE = 0,
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_SATURATION,
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_CONTRAST,
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_BRIGHTNESS,
};
enum
{
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_VO_HUE = 0,
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_VO_SATURATION,
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_VO_CONTRAST,
	EM_CONFIG_PREVIEW_PARAM_PREVIEWCOLOR_VO_BRIGHTNESS,
};

//osd
#define CONFIG_OSD_PARAM				"OSD"
#define CONFIG_OSD_PARAM_SHOWTIME		"ShowTime"
#define CONFIG_OSD_PARAM_TIME_X			"TimePosX"
#define CONFIG_OSD_PARAM_TIME_Y			"TimePosY"
#define CONFIG_OSD_PARAM_SHOWRECSTATE	"ShowRecState"
#define CONFIG_OSD_PARAM_SHOWCHNKBPS	"ShowChnKbps"
#define CONFIG_OSD_PARAM_STR_OSD		"StrOsd"
#define CONFIG_OSD_PARAM_RECT_OSD		"RectOsd"
enum
{
	EM_CONFIG_OSD_PARAM_STR_OSD_CHNNAME = 0,
	EM_CONFIG_OSD_PARAM_STR_OSD_SHOW_CHNNAME,
	EM_CONFIG_OSD_PARAM_STR_OSD_CHNNAME_X,
	EM_CONFIG_OSD_PARAM_STR_OSD_CHNNAME_Y,
	EM_CONFIG_OSD_PARAM_STR_OSD_ENC_SHOW_CHNNAME,
	EM_CONFIG_OSD_PARAM_STR_OSD_ENC_CHNNAME_X,
	EM_CONFIG_OSD_PARAM_STR_OSD_ENC_CHNNAME_Y,
	EM_CONFIG_OSD_PARAM_STR_OSD_ENC_SHOWTIME,
	EM_CONFIG_OSD_PARAM_STR_OSD_ENC_TIME_X,
	EM_CONFIG_OSD_PARAM_STR_OSD_ENC_TIME_Y,
};
enum
{
	EM_CONFIG_OSD_PARAM_RECT_OSD_SHOW = 0,
	EM_CONFIG_OSD_PARAM_RECT_OSD_NUM,
	EM_CONFIG_OSD_PARAM_RECT_OSD_X,
	EM_CONFIG_OSD_PARAM_RECT_OSD_Y,
	EM_CONFIG_OSD_PARAM_RECT_OSD_W,
	EM_CONFIG_OSD_PARAM_RECT_OSD_H,
};

//encode
#define CONFIG_ENCODE_PARAM			"VideoEnc"
#define CONFIG_ENCODE_PARAM_MAIN	"VideoEncMain"
#define CONFIG_ENCODE_PARAM_SUB	"VideoEncSub"
#define CONFIG_ENCODE_PARAM_MOB	"VideoEncMob"

enum
{
	EM_CONFIG_ENCODE_PARAM_BITRATE = 0,
	EM_CONFIG_ENCODE_PARAM_FRAMERATE,
	EM_CONFIG_ENCODE_PARAM_GOP,
	EM_CONFIG_ENCODE_PARAM_MINQP,
	EM_CONFIG_ENCODE_PARAM_MAXQP,
	EM_CONFIG_ENCODE_PARAM_RESULUTION,
	EM_CONFIG_ENCODE_PARAM_ENCODETYPE,
	EM_CONFIG_ENCODE_PARAM_BITERATETYPE,
	EM_CONFIG_ENCODE_PARAM_PICLEVEL,	
};

//record
#define CONFIG_RECORD_PARAM		"Rec"
#define CONFIG_RECORD_PARAM_REC	"Rec"
enum
{
	EM_CONFIG_RECORD_PARAM_REC_STREAMTYPE = 0,
	EM_CONFIG_RECORD_PARAM_REC_ENCCHN,
	EM_CONFIG_RECORD_PARAM_REC_ENCCHN_TYPE,
	EM_CONFIG_RECORD_PARAM_REC_PRETIME,
	EM_CONFIG_RECORD_PARAM_REC_DELAYTIME,
	EM_CONFIG_RECORD_PARAM_REC_EXPIRE,
	EM_CONFIG_RECORD_PARAM_REC_SCHTYPE_TIMER,
	EM_CONFIG_RECORD_PARAM_REC_SCHTYPE_MOTION,
	EM_CONFIG_RECORD_PARAM_REC_SCHTYPE_SENSOR,
	EM_CONFIG_RECORD_PARAM_REC_ENABLE,
	EM_CONFIG_RECORD_PARAM_REC_RECORDING,
};

//sensor
#define CONFIG_SENSOR_PARAM				"Sensor"
//yaogang modify 20141010
#define CONFIG_IPCCOVER_PARAM			"IPCCover"
#define CONFIG_IPCExtSENSOR_PARAM		"IPCExtSensor"
#define CONFIG_485ExtSENSOR_PARAM		"485ExtSensor"
#define CONFIG_HDD_PARAM				"HDDAlarm"

#define CONFIG_SENSOR_PARAM_SENSOR		"Sensor"
//yaogang modify 20141209 深广平台参数
#define CONFIG_SG_PARAM				"ShenGuang"
#define CONFIG_SG_PARAM_SG			"Para"
//yaogang modify 20150105 Snap
#define CONFIG_SNAP_PARAM				"SnapParam"
#define CONFIG_SNAP_PARAM_CHN			"Chn"

//yaogang modify for bad disk
#define CONFIG_BAD_DISK_PARAM				"BadDiskList"
#define CONFIG_BAD_DISK_PARAM_LINE			"Disk"


enum
{
	EM_CONFIG_SG_PARAM_AgentID = 0,
	EM_CONFIG_SG_PARAM_CenterIP,
	EM_CONFIG_SG_PARAM_RunEnable,
	EM_CONFIG_SG_PARAM_AlarmEnable,
	EM_CONFIG_SG_PARAM_DailyPicEnable,
	EM_CONFIG_DVR_EXIT_NORMOAL,
};
enum
{
	EM_CONFIG_SG_PARAM_PreTimes=0,
	EM_CONFIG_SG_PARAM_Interval,
	EM_CONFIG_SG_PARAM_StillTimes,
	EM_CONFIG_SG_PARAM_IpcChn,
};
enum
{
	EM_CONFIG_SG_PARAM_Time1Enable=0,
	EM_CONFIG_SG_PARAM_Time1Hour,
	EM_CONFIG_SG_PARAM_Time1Min,
	EM_CONFIG_SG_PARAM_Time1Sec,
	EM_CONFIG_SG_PARAM_Time2Enable,
	EM_CONFIG_SG_PARAM_Time2Hour,
	EM_CONFIG_SG_PARAM_Time2Min,
	EM_CONFIG_SG_PARAM_Time2Sec,
	EM_CONFIG_SG_PARAM_IpcChn1,
	EM_CONFIG_SG_PARAM_IpcChn2,
};


enum
{
	EM_CONFIG_SENSOR_PARAM_ENABLE = 0,
	EM_CONFIG_SENSOR_PARAM_TYPE,
	EM_CONFIG_SENSOR_PARAM_DELAY,
	EM_CONFIG_SENSOR_PARAM_SCHTYPE,
	EM_CONFIG_SENSOR_PARAM_NAME,
	EM_CONFIG_SENSOR_PARAM_FLAG_BUZZ,
	EM_CONFIG_SENSOR_PARAM_ZOOMCHN,
	EM_CONFIG_SENSOR_PARAM_FLAG_MAIL,
	EM_CONFIG_SENSOR_PARAM_SNAPCHN,
	EM_CONFIG_SENSOR_PARAM_ALARMOUT,
	EM_CONFIG_SENSOR_PARAM_RECCHN,
	EM_CONFIG_SENSOR_PARAM_PTZTYPE,
	EM_CONFIG_SENSOR_PARAM_PTZCHN,
	EM_CONFIG_SENSOR_PARAM_PTZID,	
};

//motion
#define CONFIG_VMOTION_PARAM			"VMotion"
#define CONFIG_VMOTION_PARAM_VMOTION	"VMotion"
enum
{
	EM_CONFIG_VMOTION_PARAM_ENABLE = 0,
	EM_CONFIG_VMOTION_PARAM_SENSITIVITY,
	EM_CONFIG_VMOTION_PARAM_DELAY,
	EM_CONFIG_VMOTION_PARAM_SCHTYPE,
	EM_CONFIG_VMOTION_PARAM_FLAG_BUZZ,
	EM_CONFIG_VMOTION_PARAM_ZOOMCHN,
	EM_CONFIG_VMOTION_PARAM_FLAG_MAIL,
	EM_CONFIG_VMOTION_PARAM_SNAPCHN,
	EM_CONFIG_VMOTION_PARAM_ALARMOUT,
	EM_CONFIG_VMOTION_PARAM_RECCHN,
	EM_CONFIG_VMOTION_PARAM_STATUS,	
	//csp modify:PTZ联动参数跟在移动侦测区域参数之后
	//EM_CONFIG_VMOTION_PARAM_PTZTYPE,
	//EM_CONFIG_VMOTION_PARAM_PTZCHN,
	//EM_CONFIG_VMOTION_PARAM_PTZID,
};

//video lost
#define CONFIG_VLOST_PARAM			"VLost"
#define CONFIG_VLOST_PARAM_VLOST	"VLost"
enum
{
	EM_CONFIG_VLOST_PARAM_ENABLE = 0,
	EM_CONFIG_VLOST_PARAM_DELAY,
	EM_CONFIG_VLOST_PARAM_SCHTYPE,
	EM_CONFIG_VLOST_PARAM_FLAG_BUZZ,
	EM_CONFIG_VLOST_PARAM_ZOOMCHN,
	EM_CONFIG_VLOST_PARAM_FLAG_MAIL,
	EM_CONFIG_VLOST_PARAM_SNAPCHN,
	EM_CONFIG_VLOST_PARAM_ALARMOUT,
	EM_CONFIG_VLOST_PARAM_RECCHN,
	EM_CONFIG_VLOST_PARAM_PTZTYPE,
	EM_CONFIG_VLOST_PARAM_PTZCHN,
	EM_CONFIG_VLOST_PARAM_PTZID,	
};

//video blind
#define CONFIG_VBLIND_PARAM			"VBlind"
#define CONFIG_VBLIND_PARAM_VBLIND	"VBlind"
enum
{
	EM_CONFIG_VBLIND_PARAM_ENABLE = 0,
	EM_CONFIG_VBLIND_PARAM_DELAY,
	EM_CONFIG_VBLIND_PARAM_SCHTYPE,
	EM_CONFIG_VBLIND_PARAM_FLAG_BUZZ,
	EM_CONFIG_VBLIND_PARAM_ZOOMCHN,
	EM_CONFIG_VBLIND_PARAM_FLAG_MAIL,
	EM_CONFIG_VBLIND_PARAM_SNAPCHN,
	EM_CONFIG_VBLIND_PARAM_ALARMOUT,
	EM_CONFIG_VBLIND_PARAM_RECCHN,
	EM_CONFIG_VBLIND_PARAM_PTZTYPE,
	EM_CONFIG_VBLIND_PARAM_PTZCHN,
	EM_CONFIG_VBLIND_PARAM_PTZID,	
};

//alarm out
#define CONFIG_ALARMOUT_PARAM			"AlarmOut"
#define CONFIG_ALARMOUT_PARAM_ALARMOUT	"AlarmOut"
enum
{
	EM_CONFIG_ALARMOUT_PARAM_ENABLE = 0,
	EM_CONFIG_ALARMOUT_PARAM_TYPE,
	EM_CONFIG_ALARMOUT_PARAM_DELAY,
	EM_CONFIG_ALARMOUT_PARAM_NAME,
	EM_CONFIG_ALARMOUT_PARAM_SCHTYPE,	
};

//buzz
#define CONFIG_BUZZ_PARAM			"Buzz"
#define CONFIG_BUZZ_PARAM_BUZZ		"Buzz"
enum
{
	EM_CONFIG_BUZZ_PARAM_ENABLE = 0,
	EM_CONFIG_BUZZ_PARAM_DELAY,
};

//ptz
#define CONFIG_PTZ_PARAM			"Ptz"
#define CONFIG_PTZ_PARAM_PTZCFG		"PtzCfg"
enum
{
	EM_CONFIG_PTZ_PARAM_CAMADDR = 0,
	EM_CONFIG_PTZ_PARAM_BAUDRATE,
	EM_CONFIG_PTZ_PARAM_DATABIT,
	EM_CONFIG_PTZ_PARAM_STOPBIT,
	EM_CONFIG_PTZ_PARAM_CHECKTYPE,
	EM_CONFIG_PTZ_PARAM_FLOWCTRLTYPE,
	EM_CONFIG_PTZ_PARAM_PROTOCOL,
	EM_CONFIG_PTZ_PARAM_PRESET,
	EM_CONFIG_PTZ_PARAM_PRESET2,
	EM_CONFIG_PTZ_PARAM_ENABLE,
	EM_CONFIG_PTZ_PARAM_TOURPATH,
	EM_CONFIG_PTZ_PARAM_TOURPATH2,
	//
};
#define CONFIG_PTZ_TOUR_PARAM			"TourPathChn"
#define CONFIG_PTZ_TOUR_PARAM_TOURPATH	"TourPath"
enum
{
	EM_CONFIG_PTZ_TOUR_PARAM_PRESETPOS = 0,
	EM_CONFIG_PTZ_TOUR_PARAM_DWELLTIME,
	EM_CONFIG_PTZ_TOUR_PARAM_SPEED,
};

//schedule
#define CONFIG_SCH_PARAM				"SchRecScheduleChn"
#define CONFIG_SCH_PARAM_REC_TIMER		"SchRecSchedule"
#define CONFIG_SCH_PARAM_REC_VMOTION	"MDRecSchedule"
#define CONFIG_SCH_PARAM_REC_SENSOR		"SensorRecSchedule"
#define CONFIG_SCH_PARAM_SENSOR			"SensorSchedule"
#define CONFIG_SCH_PARAM_IPCEXTSENSOR			"IPCExtSensorSchedule"

#define CONFIG_SCH_PARAM_VMOTION		"MDSchedule"
#define CONFIG_SCH_PARAM_ALARMOUT		"AlarmoutSchedule"
enum
{
	EM_CONFIG_SCH_PARAM_STARTTIME = 0,
	EM_CONFIG_SCH_PARAM_ENDTIME,
};

//user
#define CONFIG_USER_PARAM				"User"
#define CONFIG_USER_PARAM_SETTED_USER	"FlagSettedUser"
#define CONFIG_USER_PARAM_USER			"User"
#define CONFIG_USER_PARAM_SETTED_GROUP	"FlagSettedGroup"				
#define CONFIG_USER_PARAM_GROUP			"Group"
enum
{
	EM_CONFIG_USER_PARAM_USER_NAME = 0,
	EM_CONFIG_USER_PARAM_USER_PASSWD,
	EM_CONFIG_USER_PARAM_USER_GROUPBELONG,
	EM_CONFIG_USER_PARAM_USER_DESCRIPT,
	EM_CONFIG_USER_PARAM_USER_LOGINTWINCE,
	EM_CONFIG_USER_PARAM_USER_BINDPCMAC,
	EM_CONFIG_USER_PARAM_USER_MACADDR,
	EM_CONFIG_USER_PARAM_USER_AUTHOR,
	//
};
enum
{
	EM_CONFIG_USER_PARAM_GROUP_NAME = 0,
	EM_CONFIG_USER_PARAM_GROUP_DESCRIPT,
	EM_CONFIG_USER_PARAM_GROUP_DOWITHUSER,
	EM_CONFIG_USER_PARAM_GROUP_AUTHOR,
	//
};

//Network
#define CONFIG_NET_PARAM				"NetworkPara"
#define CONFIG_NET_PARAM_CONFIG			"NetworkConfig"
#define CONFIG_NET_PARAM_STREAM			"NetworkStream"
#define CONFIG_NET_PARAM_MAIL			"NetworkMail"
#define CONFIG_NET_PARAM_MORE			"NetworkMoreConfig"

enum
{
	EM_CONFIG_NET_CONFIG_VERSION = 0,
	EM_CONFIG_NET_CONFIG_HOSTNAME,
	EM_CONFIG_NET_CONFIG_IP,
	EM_CONFIG_NET_CONFIG_SUBMASK,
	EM_CONFIG_NET_CONFIG_GATEWAY,
	EM_CONFIG_NET_CONFIG_DNSIP,
	EM_CONFIG_NET_CONFIG_DNSIPALT,
	EM_CONFIG_NET_CONFIG_MAC,
	EM_CONFIG_NET_CONFIG_ALARMSERVER_IP,
	EM_CONFIG_NET_CONFIG_ALARMSERVER_PORT,
	EM_CONFIG_NET_MAIL_SMTP_IP,
	EM_CONFIG_NET_MAIL_SMTPPORT,
	EM_CONFIG_NET_MAIL_LOGSERVER_IP,
	EM_CONFIG_NET_MAIL_LOGSERVER_PORT,
	
	EM_CONFIG_NET_CONFIG_HTTPPORT,
	EM_CONFIG_NET_CONFIG_MOBILEPORT,
	
	EM_CONFIG_NET_CONFIG_TCPCONN_MAX,
	
	EM_CONFIG_NET_CONFIG_SERVERPORT,
	EM_CONFIG_NET_CONFIG_SUBSTREAMMAX,
	EM_CONFIG_NET_CONFIG_BUFPERCHN,
	EM_CONFIG_NET_CONFIG_FRAMESIZEMAX,
	EM_CONFIG_NET_CONFIG_VMEDIA_TYPE,
	EM_CONFIG_NET_CONFIG_AMEDIA_TYPE,
	EM_CONFIG_NET_CONFIG_VOIPMEDIA_TYPE,
	EM_CONFIG_NET_CONFIG_AUDIO_MODE,
	
	EM_CONFIG_NET_CONFIG_SSL_PORT,
	EM_CONFIG_NET_CONFIG_UDP_PORT,
	
	EM_CONFIG_NET_CONFIG_MCAST_FLAG,
	EM_CONFIG_NET_CONFIG_MCAST_PORT,
	EM_CONFIG_NET_CONFIG_MCAST_IP,
	
	EM_CONFIG_NET_CONFIG_PPPOE_FLAG,
	EM_CONFIG_NET_CONFIG_POE_USER,
	EM_CONFIG_NET_CONFIG_POE_PASSWD,
	
	EM_CONFIG_NET_CONFIG_DHCP_FLAG,
	EM_CONFIG_NET_CONFIG_DDNS_FLAG,
	
	EM_CONFIG_NET_CONFIG_DDNS_DOMAIN,
	EM_CONFIG_NET_CONFIG_DDNS_USER,
	EM_CONFIG_NET_CONFIG_DDNS_PASSWD,
	
	EM_CONFIG_NET_CONFIG_UPDATEINTERVAL,
	
	EM_CONFIG_NET_CONFIG_MONITOR_MODE,
	
	EM_CONFIG_NET_CONFIG_PLAY_MODE,
	EM_CONFIG_NET_CONFIG_ALARMCENTER_STATE,
	
	EM_CONFIG_NET_MAIL_SENDMAILBOX,
	EM_CONFIG_NET_MAIL_PASSWD,
	EM_CONFIG_NET_MAIL_SSL_FLAG,
	EM_CONFIG_NET_MAIL_RECVMAILBOX,
	EM_CONFIG_NET_MAIL_RECVMAILBOX1,
	EM_CONFIG_NET_MAIL_RECVMAILBOX2,
	EM_CONFIG_NET_MAIL_SNAPPIC,	
	EM_CONFIG_NET_MAIL_SNAPINTERVAL,
	
	//csp modify 20130321
	EM_CONFIG_NET_CONFIG_UPNP_FLAG,
};

#endif //_USER_CONFIG_H_

